[Fia] step 3 구현
codesquad-members-2023/be-java-cafe-max pull request #105
Opened 2023-04-07 09:19 UTC by yeonise

안녕하세요, Cooper! 2주차 PR 보냅니다.

## 이번 주 진행 상황

1. **1주차 Review를 바탕으로 개선하기**
- `REAME.md` 에서 학습 계획을 제거하기
학습 계획은 notion에서 따로 작성합니다. [2주차 학습 계획](https://yeonise.notion.site/4-3-Mission-3-0cebadc32719453695b5d4655e8c3b68)
- DTO 사용하기
- Service 사용하기
- 전체적인 view 개선하기
- `@ControllerAdvice` 를 사용하여 예외 처리하기
- 사용자 정의 예외 클래스 구현하기

2. **mission step-3을 구현하기**
step-3 단계에서 진행하는 것은 다음과 같습니다.
- JDBC를 이용하여 h2 데이터베이스 사용하기
- AWS EC2를 이용하여 배포하기 [Fia의 CodeSquad](http://43.201.78.83:8080/)

## 고민

**1. DTO의 사용 범위에 대하여**

`DTO와 Domain 간의 변환 위치로서는 Controller가 적합하다. vs Service가 적합하다.`
[두 가지 의견](https://tecoble.techcourse.co.kr/post/2021-04-25-dto-layer-scope/)에 대해 더 학습해보려고 하는데, 혹시 조언이나 의견이 있으신가요? 🤔

**2. 기본 생성자와 getter / setter**

`BeanPropertySqlParameterSource` 를 사용하여 매핑을 하려고 보니,
비어있는 기본 생성자를 사용하여 객체를 생성하고 → resultSet으로 받은 값을 setter를 사용해서 값을 설정하는 것 같더라구요.

따라서 기존에 없던 기본 생성자와 setter를 추가하게 됐습니다.

setter를 사용하는 대신, 파라미터를 받는 생성자를 사용하여 매핑하는 방법을 사용해 볼까 했는데
다음과 같은 이유로 선호하지 않는 경우도 있다고 합니다.
- 생성자를 이용한 방법은 코드의 가독성이 떨어질 수 있음
- 파라미터의 순서가 변경되면 코드 수정이 필요함
- null 값 처리가 어려울 수 있음

그래서 일단은 직관적이고 편리한 BeanPropertySqlParameterSource를 사용하여 구현했습니다.
setter의 사용이 어디까지가 적합한지 아직 감이 잘 안잡혀서 고민이 됩니다.

**3. 사용자 예외 처리 관리**

사용자 예외를 계속해서 만들다 보면 생기는 관리의 어려움을 해결하고자,
`Enum` 클래스를 사용하여 구현하신 분도 있더라구요.

``` java
public enum UserExceptionType {
    DUPLICATED_USER_ID("error-userId", "이미 존재하는 아이디입니다"),
    DUPLICATED_EMAIL("error-email", "이미 존재하는 이메일입니다."),
    NOT_MATCHED_BEFORE_PASSWORD("error-password", "비밀번호가 일치하지 않습니다.");

    private final String category;
    private final String message;

    UserExceptionType(String category, String message) {
        this.category = category;
        this.message = message;
    }

    public String getCategory() {
        return category;
    }

    public String getMessage() {
        return message;
    }
```

이렇게 공통된 하나의 사용자 예외에 type을 받아서 사용하는 방식입니다.

``` java
public class UserFormInputException extends RuntimeException {
    private final UserExceptionType userExceptionType;
    private final UserFormDto userFormDto;

    public UserFormInputException(UserExceptionType userExceptionType, UserFormDto userFormDto) {
        this.userExceptionType = userExceptionType;
        this.userFormDto = userFormDto;
    }

    public UserExceptionType getUserExceptionType() {
        return userExceptionType;
    }

    public UserFormDto getUserFormDto() {
        return userFormDto;
    }
}
```

- 각각의 사용자 예외를 만드는 경우,
특정한 하나의 예외 내부를 변경할 때, 해당 클래스만 변경하면 된다는 점에서 변경의 이유가 확실하다.

- 공통된 사용자 예외와 enum을 사용하여 관리하는 경우
그룹화되어 관리하기 편리하다.

이 외에도 enum을 사용하여 관리하면 얻는 이점이 있을까요? 언제 어떻게 enum 활용하면 좋을지 고민이 돼요.

아직 부족한 부분이 많아서 무언가를 선택해야 하는 상황이 오면 `어떤 것이 지금 더 적합하다` 는 결정을 내리지 못하는 것 같아요.
공부를 더 해야겠습니다. 🧐
이번 주도 긴 글 읽어주셔서 감사합니다 : )

2023-04-08 08:25 UTC, pbg0205 requested changes
안녕하세요 피아~ 리뷰어 쿠퍼입니다 🖐
이번주에 작업해준 내용 확인보니까 코드가 정말 깔끔하게 작성하셨더라구요!
전반적으로 잘 정리된 코드 덕분에 감탄하면서 리뷰할 수 있었던 것 같아요. 다음주에는 또 어떤 부분을 더 개선해 나가실지 궁금해지네요 😃
PR 에 올려주신 질문들에 관련된 답변부터 드릴게요!

### DTO 의 사용 영역

1. DTO 를 사용하는 이유는 네이밍 그대로 **데이터를 전달하기 위한 책임**을 가지고 있어요. 데이터를 전달하기 위한 책임을 DTO 에게 부여한 이유는 도메인 객체에게 데이터를 전달해 도메인 객체가 비즈니스 로직을 처리 위함이라고 생각합니다.
2. 그렇다면 도메인 객체는 비즈니스 로직을 담당하는 공간인 Service 레이어에 존재해야 한다고 생각합니다. Controller 의 책임은 응답을 반환하고 요청 값에 대한 검증을 하는 담당하는 부분이기 때문에 DTO로 변환하는 부분은 서비스 레이어에서 처리되어야 되지 않을까 하는 의견이에요  😃

### NamedParameterJdbcTemplate

1. 이 부분은 NamedParameterJdbcTemplate 를 사용하면 불가피하게 사용해야 하는 것 같아요. docs 에도 기본 생성자는 필수로 선언을 해야 하기 떄문에 불가피한 것 같네요ㅠ  이렇게 특정 기술에 관련해서 생성자나 setter 를 사용하는 경우가 있어서 기술 검토를 할 떄 이와 같은 요소도 검토 내용으로 고려되고 있어요~ NamedParamaterJdbcTemplate 를 적용해주신 방법은 좋은 시도라고 생각하고 저도 한번 더 좋은 방법에 대해 고민해볼게요~

### 예외에 관한 고민

1. 예시로 들어주신 Enum 의 용도는 메세지를 묶기 위한 목적인 것 같아서 저는 그렇게 큰 의미는 없는 것 같아요~ 지금 작성해주신대로 커스텀 예외만 선언해주셔도 될 것 같습니다! 


특정 기술이나 적용 방식의 선택은 경험의 영역이라 선택이 어려운 것은 당연한 것 같아요~ 현재 구조에서 더 나은 방식을 고민해보시는 시도 자체가 충분히 의미있다고 생각합니다. 계속해서 시도해보시면서 특정 기술이나 적용 방법에 관한 장단점에 대해 나름대로 정리하는 연습해보시면 좋은 개발자로 성장하실 거에요 👍👍👍화이팅임다 🫡 작성하시다가 궁금한 점이나 같이 고민해보고 싶은 부분있으면 언제든 편하게 DM 주세요!

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/ArticleService.java
> +    }
아마 MemoryArticleRepository 에서 JdbcArticleRepository 로 변경하시면서 빈 충돌이 있어서 MemoryArticleRepository 에 @Repository 어노테이션을 제거하신 것 같아요. 이 부분은 `@Qualifier` 을 사용하시면 해결할 수 있습니다! 옵션으로 빈 이름을 선언하시면 특정 빈에 관해 의존성을 주입해줘요! 이 부분도 추가적으로 학습해보시면 좋을 것 같습니다 😃

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/dto/article/ArticleSaveRequest.java
> +
불변을 위해 final 키워드를 추가해주시면 좋을 것 같아요!

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/ArticleService.java
> +        return articleRepository.findAll().stream().map(ArticleResponse::from).collect(Collectors.toUnmodifiableList());
stream API 좋네요 👍👍

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/repository/user/JdbcUserRepository.java
> +    }
[참고만 해주세요!] count() 함수는 내부적으로 풀테이블 스캔으로 동작하는데 테이블의 모든 row를 탐색합니다. 특정 데이터의 유뮤를 확인하는 다른 방법으로는 limit 를 활용하는 방법이 있는데요. limit 의 경우에는 원하는 row 를 찾은 다음에 스캔을 멈추기 때문에 성능상 이점이 있습니다. 지금도 충분히 잘 구현해주셨고 관련된 내용만 다음에 DB 공부하실 때 참고하시면 좋을 것 같아서 코멘트 드립니다 😃
```sql
SELECT id FROM users LIMIT 1;
```

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/repository/user/JdbcUserRepository.java
> +        final String SQL = "SELECT * FROM users WHERE userId = :userId";
지연 변수는 소문자로 변경 해주세요 😃

2023-04-08 08:25 UTC, pbg0205 commented on src/main/resources/application.yml
> +    url: jdbc:h2:file:~/test
파일을 탐색하는 방식으로 되어 있어서 로컬에서 실행이 안돼네요ㅠ in-memory 로 설정 변경해주세요
- [Connecting to an Embedded (Local) Database](http://www.h2database.com/html/features.html#embedded_databases)
```properties
jdbc:h2:~/testdb
```

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/repository/article/JdbcArticleRepository.java
> +    }
확인해보니까 `JdbcTemplateAutoConfiguration` 에서 `NamedParameterJdbcTemplate` 를 빈으로 선언하고 있어서 생성자 주입으로 변경하셔도 될 것 같아요!
```java
    public JdbcArticleRepository(NamedParameterJdbcTemplate namedParameterJdbcTemplate) {
        this.jdbcTemplate = namedParameterJdbcTemplate;
    }
```

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/exception/AllExceptionHandler.java
> +@ControllerAdvice
이전에 코멘트 드렸던 `@ControllerAdvice` 진행해주셨네요 👍👍

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/ExceptionController.java
> +}
이 부분은 어디에서 사용하는건가요??

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/exception/user/MismatchedPasswordException.java
> +        super("비밀번호가 일치하지 않습니다.");
매직 스트링은 상수로 변경해주세요!

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +        if (!userRepository.findByUserId(userUpdateRequest.getUserId()).isPasswordMatched(userUpdateRequest.getCurrentPassword())) { // 현재 비밀번호 일치 여부 검사
만약 사용자를 찾지 못했을 경우에는 null 이 반환되서 예외가 발생할 것 같아요!

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/exception/user/MismatchedPasswordException.java
> +    private final UserUpdateRequest userUpdateRequest;
예외에 관한 정보를 인스턴스 필드에 가지고 있는 방법도 신기하네요😃 개인적인 생각으로는 수정를 위한 정보를 예외 클래스에서 가지고 있는 부분이 적절한 책임인지에 관한 의문이 좀 있어서 이 부분은 우선 유지하고 조금 더 같이 고민해보시죠 🤔

2023-04-08 08:25 UTC, pbg0205 commented on src/test/java/kr/codesqaud/cafe/repository/MemoryArticleRepositoryTest.java
>      @Test
@DiaplayName 어노테이션을 사용해보시는 것도 고민해보시면 좋을 것 같아요! 테스트의 의미를 명확하게 전달할 수 있는 장점이 있습니다ㅎㅎ

2023-04-08 08:25 UTC, pbg0205 commented on src/test/java/kr/codesqaud/cafe/repository/MemoryArticleRepositoryTest.java
>      MemoryArticleRepository memoryArticleRepository = new MemoryArticleRepository();
이 부분은 @BeforeEach 에서 객체를 생성하는 로직이 있어서 제거해주셔도 될 것 같아요!

2023-04-08 08:25 UTC, pbg0205 commented on src/test/java/kr/codesqaud/cafe/repository/MemoryUserRepositoryTest.java
>      MemoryUserRepository memoryUserRepository = new MemoryUserRepository();
이 부분도 @BeforeEach 에서 객체를 생성하는 로직이 있어서 제거해주셔도 될 것 같아요!

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/exception/article/ArticleNotFoundException.java
> +        super("존재하지 않는 게시글입니다.");
매직 스트링은 상수로 전환해주세요 🙏

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/exception/user/DuplicateUserIdException.java
> +        super("이미 사용 중인 아이디입니다.");
매직 스트링은 상수로 전환해주세요 🙏

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/exception/user/UserNotFoundException.java
> +        super("존재하지 않는 회원입니다.");
매직 스트링은 상수로 전환해주세요 🙏

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/exception/user/UserNotFoundException.java
> +public class UserNotFoundException extends RuntimeException {
의미가 명확한 커스텀 예외 네이밍👍👍

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/exception/user/DuplicateUserIdException.java
> +public class DuplicateUserIdException extends RuntimeException {
`AlreadyUserExistenceException` 네이밍도 한번 생각해봤는데 참고만 해보시고 더 괜찮은 것 같은 네이밍으로 사용하시면 될 것 같아요!

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/repository/article/ArticleRepository.java
> +    boolean isExists(Long id);
exist가 동사인걸로 알고 있어서 `existsArticle` 또는 `exist` 도 괜찮을 것 같아요!

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/repository/article/JdbcArticleRepository.java
> +    public boolean isExists(Long id) {
exist가 동사인걸로 알고 있어서 `exist` 또는 `existArticle` 네이밍은 어떠세요??

2023-04-08 08:25 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +    public void saveUser(UserSaveRequest userSaveRequest) throws DuplicateUserIdException { // 새로운 회원 저장하기
예외를 위임한 이유에 대해서 궁금합니다🤔

2023-04-09 06:10 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/service/ArticleService.java
> +    }
`@Primary` 를 사용하거나 Config 파일에서 직접 설정을 바꿔주는 방법보다
실제로 객체를 사용하는 service에서 어떤 빈 객체를 주입받을지 정해주니, 로직이 어떤 repository를 기준으로 동작하는지 바로 보여서 좋은 것 같아요!
일단 삭제했던 `@Repository` 를 다시 추가하고, service 생성자의 파라미터에 `@Qualifier` 를 사용하여 빈을 지정해주었습니다.
더 알아보겠습니다 🫡

2023-04-09 06:17 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/dto/article/ArticleSaveRequest.java
> +
다른 분들의 코드를 보니, final이나 stream 같은 것들을 사용해서 불변을 신경써서 작성하시는 것 같더라구요..!
자꾸 잊어버리는 부분인데 다시 학습해야겠습니다
그리고 인텔리제이에서 final을 우선적으로 붙여주는 기능도 있다길래 일단 도움을 받기로 했습니다 ㅎㅎ

<img width="441" alt="스크린샷 2023-04-08 오후 11 52 57" src="https://user-images.githubusercontent.com/105152276/230757750-0d272094-bd02-4cbe-83e0-455470c3162f.png">

2023-04-09 06:23 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/service/ArticleService.java
> +        return articleRepository.findAll().stream().map(ArticleResponse::from).collect(Collectors.toUnmodifiableList());
stream을 사용할 수 있으면 사용하는 게 좋을까요?
반복 연산이 많지 않거나, 중간 연산 결과가 필요 없는 경우에는 일반적으로 람다나 스트림을 사용하나요? 🤔

2023-04-09 06:32 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/repository/user/JdbcUserRepository.java
> +    }
감사합니다 😊 찾아보니 이동욱님 블로그에도 조언해주신 것과 같은 설명이 있네요!
`SELECT id` 로 작성하신 것처럼 `*` 도 사용을 지양해야겠습니다

<img width="769" alt="스크린샷 2023-04-09 오후 3 25 15" src="https://user-images.githubusercontent.com/105152276/230758018-bb0ea7f8-b859-405d-b1d8-83cd3217488f.png">

2023-04-09 06:35 UTC, yeonise commented on src/main/resources/application.yml
> +    url: jdbc:h2:file:~/test
in-memory로 작업하다가 프로그램을 다시 실행하면 데이터가 사라져서 파일로 변경했는데 혹시 대신 DB 파일을 github에 추가해서 올려도 될까요? 🥲

2023-04-09 06:43 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/controller/ExceptionController.java
> +}
`users/{userId}` 또는 `articles/{id}` 와 같이 해당 유저나 게시글을 찾을 때,
`{userId}` , `{id}` 가 존재하지 않는 경우 발생하는 예외를
`@ControllerAdvice` 로 처리해서 다음과 같이 실패 페이지를 보여주려고 사용했습니다

``` java
    @ResponseStatus(HttpStatus.NOT_FOUND)
    @ExceptionHandler(UserNotFoundException.class)
    public String handleUserNotFoundException(UserNotFoundException exception, Model model) {
        model.addAttribute("failMessage", exception.getMessage());
        return "exception/fail";
    }

    @ResponseStatus(HttpStatus.NOT_FOUND)
    @ExceptionHandler(ArticleNotFoundException.class)
    public String handelArticleNotFoundException(ArticleNotFoundException exception, Model model) {
        model.addAttribute("failMessage", exception.getMessage());
        return "exception/fail";
    }
```

적합한 위치를 찾지 못해서 따로 Controller를 만들어 사용했는데 불필요해 보일까요? 🤔

2023-04-09 06:46 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/exception/user/MismatchedPasswordException.java
> +        super("비밀번호가 일치하지 않습니다.");
field에 static final을 사용하여 변경하겠습니다 🙆🏻

2023-04-09 06:49 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/exception/user/MismatchedPasswordException.java
> +    private final UserUpdateRequest userUpdateRequest;
넵! 고민해보겠습니다 🤔

2023-04-09 06:52 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/exception/user/DuplicateUserIdException.java
> +public class DuplicateUserIdException extends RuntimeException {
중복된 두 사용자가 존재하는게 아니라, 이미 해당 아이디를 사용하는 회원이 존재하고 있음을 알린다는 의미에서 `AlreadyUserExistenceException` 가 더 괜찮은 것 같아요 🙆🏻

2023-04-09 06:53 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/repository/article/ArticleRepository.java
> +    boolean isExists(Long id);
앗 그렇네요! 수정하겠습니다!

2023-04-09 06:53 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/repository/article/JdbcArticleRepository.java
> +    public boolean isExists(Long id) {
마찬가지로 수정하겠습니다 🙆🏻

2023-04-09 06:58 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +    public void saveUser(UserSaveRequest userSaveRequest) throws DuplicateUserIdException { // 새로운 회원 저장하기
앗 코드를 이것저것 작성해보다가 들어갔던 것을 확인하지 못한 것 같습니다
검토를 더 꼼꼼히 해야겠네요 🥺 제거했습니다!

2023-04-09 07:03 UTC, yeonise commented on src/test/java/kr/codesqaud/cafe/repository/MemoryArticleRepositoryTest.java
>      @Test
`@DisplayName` 에 `~을 확인하는 테스트` 와 같은 형식으로 추가해보겠습니다 ㅎㅎ

2023-04-09 07:07 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/ArticleService.java
> +        return articleRepository.findAll().stream().map(ArticleResponse::from).collect(Collectors.toUnmodifiableList());
개발자 분들마다 선호하는 방식이 다르겠지만 복잡한 요구사항이 아니라면 stream 을 사용했을 때
가독성이 더 좋은 것 같아서 stream 을 사용하는 편이에요! 전반적으로 가능하다면 저는 stream을 지향하는 편입니다 😃

2023-04-09 07:11 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +        if (!userRepository.findByUserId(userUpdateRequest.getUserId()).isPasswordMatched(userUpdateRequest.getCurrentPassword())) { // 현재 비밀번호 일치 여부 검사
음... `findByUserId` 메서드에 Optional을 적용해보고 다음 주 PR에 반영하도록 하겠습니다 💡
pair review 때도 Optional 얘기가 나왔었는데 좀 더 공부해보고 사용해볼게요!

2023-04-09 07:21 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/dto/article/ArticleSaveRequest.java
> +
오 이 옵션은 처음보네요ㅎㅎ 저도 덕분에 하나 알아갑니다 👍

2023-04-09 07:32 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/ExceptionController.java
> +}
`@ControllerAdvice` 에서 처리하고 있어서 ExceptionController 는 없어도 될 것 같아요~
혹시 몰라서 확인해봤는데 정상 동작하네요 😃

2023-04-09 07:39 UTC, pbg0205 commented on src/main/resources/application.yml
> +    url: jdbc:h2:file:~/test
<img width="652" alt="image" src="https://user-images.githubusercontent.com/48561660/230760423-7475746d-aaaa-4278-9cb9-672738527674.png">

2023-04-09 07:40 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/repository/article/JdbcArticleRepository.java
> +    }
그렇네요!! 공식 문서를 잘 확인해야겠습니다 변경해도 잘 동작해요! 💡

<img width="565" alt="스크린샷 2023-04-09 오후 4 35 16" src="https://user-images.githubusercontent.com/105152276/230760339-0d318b28-ea79-42df-9673-58a526e85542.png">

2023-04-09 07:47 UTC, yeonise commented on src/main/java/kr/codesqaud/cafe/controller/ExceptionController.java
> +}
정말 제거해도 정상 동작하네요! 안돼서 추가했었는데 제가 뭔가 잘못했었나봅니다...ㅎㅎ
감사합니다 제거했습니다 🙆🏻

2023-04-09 09:35 UTC, yeonise commented
cooper!
바로 수정할 수 있는 부분들은 반영했습니다 나머지는 더 학습한 다음에 3주차 PR에 함께 보낼게요!
이번 주도 꼼꼼하게 봐주셔서 감사합니다 ㅎㅎ 🙇🏻
좋은 주말 저녁 보내세요 🌿

2023-04-09 11:12 UTC, pbg0205 approved these changes
넵ㅎㅎ 수고 많으셨습니다 피아!
워낙 열정적이셔서 덕분에 의욕적으로 피드백 드릴 수 있는 것 같아요. 감사합니다 👍
주말 마무리 잘하시고 다음주에 뵐게요 👋

2023-04-09 11:12 UTC, merged