[지구] Step-4 로그인, 로그아웃 구현(完) / 추가 요구사항 구현(中)
codesquad-members-2023/be-java-cafe-max pull request #138
Opened 2023-04-14 08:39 UTC by Ojeegu

안녕하세요, Cooper. 3주간 리뷰를 받게 된 지구라고 합니다.
잘 부탁드립니다.😀

---

### 구현사항
- 로그인 세션 저장
- 로그인 쿠키 저장
- 로그인 후 navbar 변경(로그인, 회원가입 → 로그아웃,정보수정)
- 기존 비밀번호 일치 시 정보 변경 가능

---

### 구현해야 할 부분
- 추가 요구사항 중 로그인한 사용자가 자신의 정보만 수정할 수 있도록 하는 것
- 예외처리(id, userId 등 잘못된 접근 시 예외 발생)
- 입력값 유효성 검사 로직 추가
- MvcConfig 활성화 시키기(get, post Mapping 동일한 url 변경)
- 배포...😥

---

### 구현 중 고민사항
- Article class의 setter를 builder pattern으로 변경하면서 articleService class의 modify method에서 수정 시 아예 새로운 객체를 생성하도록 구현했습니다. 이전 방식은 원래 있던 객체에 setter로 새로운 내용만 덮어씌웠는데, builder로 새로운 객체를 생성하는 것이 메모리 낭비가 심하지는 않은지, entity 개념에 부합한지 모르겠습니다.
- DTO가 제대로 동작하려면 기본 생성자가 필요하다고 알고 있는데 사용하지 않는 기본 생성자를 만드는 것이 코드 가독성 상 괜찮을까요?

---

### URL
| HTTP Method |        URL         |          기능           |
| :---------: | :----------------: | :---------------------: |
|     GET     |         /          |    게시글 목록 조회    |
|     GET     |      /user/join      |     회원가입 폼     |
|     POST     |   /user/join      |      회원가입     |
|     GET     |      /users/list      |     회원 목록 조회     |
|     GET     |     /users/{id}     |       프로필 조회       |
|     GET     | /users/{id}/modify |   회원 프로필 수정 폼   |
|     PUT     |   /users/{id}/modify    |    회원 프로필 수정    |
|     GET     |    /post/write    |     게시글 작성 폼      |
|    POST    |    /post/write    |     게시글 작성     |
|     GET     |    /posts/{id}/show     |    게시글 상세 조회     |
|     GET     | /posts/{id}/modify |     게시글 수정 폼      |
|     POST     | /posts/{id}/modify |     게시글 수정      |
|     GET     |       /login       |    로그인 폼     |
|     POST     |       /login       |    로그인     |
|     POST     |       /logout       |    로그아웃     |

<br>

2023-04-14 15:59 UTC, pbg0205 requested changes
안녕하세요 지구! 리뷰어 쿠퍼입니다. 앞으로 3주간 잘 부탁드려요ㅎㅎ
리뷰를 받는 것 보다 더 나은 방식에 관해 같이 고민하는 사람으로 생각해주셨으면 좋겠습니다 😄
자바와 스프링이 익숙하지 않으시다고 들었는데 충분히 잘해주고 계시는 것 같아요~
지금 회원가입 부분이 동작을 확인하면서 피드백 드리고 싶은데 지금 동작하지 않네요ㅠ
한번 검토해보시고 수정 되시면 DM 한번 부탁드려요~

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/dto/ArticleDTO.java
> +//    }
불필요한 주석은 제거해주세요~

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/dto/JoinDTO.java
> +
final 선언 좋네요 👍👍 final 키워드를 사용했을 때의 장점은 무엇일까요?

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/dto/JoinDTO.java
> +
[이 부분은 참고만 해주세요!] 현재 작업해주신 내용 잘 구현해주셨어요! 조금 더 생각할 요소에 관해 말씀드리면 크게 `fromEntity` 와 `toEntity` 메서드를 많이 사용하시는데 두 메서드를 선언했을 때의 장단점에 대해서 고민해주셔도 좋을 것 같아요! (hint: 두 메서드의 차이는 의존성의 방향의 차이인데 어떤 구조가 변경에 유연할지에 관해 한번 생각해보시는걸 추천드립니다ㅎㅎ (감이 잘 안오시면 편하게 말씀해주셔도 됩니다😃))

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/dto/ModifiedUserDTO.java
> +    }
사용하지 않는 코드는 제거해주시면 좋을 것 같아요 😃

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
>      @PostMapping("/post/write")
HTTP Method `POST` 는 생성의 의미를 담고 있어서 write 의미와 중복되서 제거해주셔도 좋을 것 같아요~
아래 참고하실만한 링크 첨부드릴게요!

-[[NHN Cloud] REST API 제대로 알고 사용하기](https://meetup.nhncloud.com/posts/92)

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
>          ArticleDTO wantedPost = articleService.clickOne(id);
`ArticleService.clickOne` 이라는 네이밍이 읽었을 때 조금 어색한 것 같아요~ `findById` 네이밍은 어떠세요?? 더 좋은 네이밍이 있으시면 언제든지 말씀해주셔도 됩니다 👍

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    @PostMapping("/posts/{id}/modify")
HTTP Method 의 `POST` 와 `PUT` 중에 `POST` 를 사용하신 의도가 궁금합니다 🤔

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    @GetMapping("/posts/{id}/show")
HTTP Method 로 `GET` 에 조회의 의미가 있어서 show 는 제거하셔도 되지 않을까 싶어요 😃

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/LoginController.java
> +    }
생성자 주입을 잘 사용해주셨네요 👍👍 스프링에서도 생성자 주입을 권장하고 있어요~ 생성자 주입을 권장하는 이유는 무엇일까요?

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/LoginController.java
> +        session.setAttribute("loginUser", loginUser);
DTO 를 세션에 추가하셨네요 👍👍

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +    public String signUp(@ModelAttribute final JoinDTO joinDTO, Model model) {
회원가입 시도할 때, `405` 가 뜨고 있네요... 확인 부탁드려요!
<img width="582" alt="image" src="https://user-images.githubusercontent.com/48561660/232085349-062df6bd-7a2d-4ae3-bbca-59be84279dd3.png">

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +        boolean isIdDuplicated = userService.checkDuplicate(joinDTO.getUserId());
지금 처리하신 부분도 충분히 좋고 중복된 아이디가 존재할 경우, 예외 처리하는 방법도 있어요! `@ControllerAdvice` 를 통해 특정 예외 처리를 할 수 있는 방법도 있습니다. 해당 컴포넌트를 사용하면 예외처리하는 부분에 관한 로직을 응집화할 수 있는 장점이 있는데 이 부분은 추후 개선 포인트로 고려해보시는 것도 좋을 것 같아요😃

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
>      @GetMapping("/users/list")
`GET` HTTP Method 에 조회라는 의미를 포함하고 있어서 `list` 는 제거해도 되지 않을까 싶은데 지구 의견은 어떠세요??

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
>          User originUser = userRepository.findById(id).orElse(null);
null 을 반환하는 방식은 최대한 지양하고 있어서 `orElseThrow()` 를 통해 예외를 활용하는 방법에 대해서도 고려해보시면 좋을 것 같아요~

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +        originUser.setEmail(modifiedUserDTO.getEmail());
setter 대신에 의미있는 메서드를 사용해보는건 어떨까요?? setter는 왜 지양할까요??

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +        return originUser.getPassword().equals(modifiedUserDTO.getOriginPassword());
equals() 메서드를 활용하는 방법도 있고 비밀번호 일치 여부 로직을 도메인 코드로 넣는 방법도 있어서 공유드려요!
```java
originUser.matchPassword(modifiedUserDTO.getOriginPassword());
```

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +                .collect(Collectors.toList());
stream api 👍👍

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/LoginController.java
> +        response.addCookie(idCookie);
쿠키를 사용하신 이유에 대해 설명 한번만 부탁드립니다 😃

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/LoginController.java
> +            session.invalidate(); // 현재 세션을 무효화
session.removeAttribute() 와 session.invalidate() 에 차이에 관해 학습해보시면 좋을 것 같습니다 🙏

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +    @PutMapping("/users/{id}/modify")
`PUT` Method 에는 수정에 관한 의미를 내포하고 있어 `modify` 는 제거해주셔도 좋을 것 같아요!

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +    public String modifyProfile(@PathVariable final long id, final ModifiedUserDTO modifiedUserDTO, final Model model) {
`@PathVariable` 은 값이 존재하지 않을 경우에는 어떻게 동작할까요?
(@PathVariable 들어가셔서(cmd + b) required option 을 한번 읽어보시면 좋을 것 같습니다😄)

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/LoginService.java
> +    public boolean checkIdAndPw(LoginDTO loginDTO) {
`checkLoginUser` 네이밍도 한번 고려해주세요ㅎㅎ (의무적으로 변경하실 필요는 없습니다!)

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/LoginService.java
> +        Optional<User> loginUser = userRepository.findByUserId(loginDTO.getUserId());
커스텀 예외를 사용하는 방법도 있어서 공유드려요! (아직 익숙하지 않으시면 참고만 해주셔도 됩니다!)
```java
User loginUser = userRepository.findByUserId(loginDTO.getUserId()).orElseThrow(() -> new AlreadyUserExistenceException());
```

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/LoginService.java
> +//    }
사용하지 않는 주석은 제거해주세요~

2023-04-14 15:59 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/ArticleService.java
> +        originArticle.setCreatedTime(articleDTO.getCreatedTime());
setter 대신의 `originArticle.update()` 메서드를 사용하는 방법도 있습니다 😃 setter 는 되도록 지양해주세요~

2023-04-16 11:07 UTC, pbg0205 approved these changes
안녕하세요 지구~ 리뷰어 쿠퍼입니다 😃
1주일동안 수고 많으셨고 피드백 드린 내용은 검토해보시고 차주에 반영해주시면 될 것 같습니다~
궁금한 사항이나 같이 고민하고 싶은 내용 있으시면 언제든 편하게 DM 주세요 👍
다음주에 뵐게요 ✋

2023-04-16 11:07 UTC, merged

2023-04-17 16:11 UTC, Ojeegu commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    @PostMapping("/posts/{id}/modify")
🙄 수정하는 걸 깜빡했습니다...!

2023-04-17 16:17 UTC, Ojeegu commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +    public String signUp(@ModelAttribute final JoinDTO joinDTO, Model model) {
🙄MvcConfig를 추가했는데 해당 URL과 Controller에 있는 PostMapping URL이 동일해서 URL 충돌이 일어난 것 같아요. PostMapping 메서드 URL 다르게 수정했습니다..!

2023-04-17 16:20 UTC, Ojeegu commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
>      @GetMapping("/users/list")
😃훨씬 깔끔해 보이고 좋아요!