[bean] 로그인 기능 구현
codesquad-members-2023/be-java-cafe-max pull request #142
Opened 2023-04-14 09:17 UTC by tjdqls1200

안녕하세요 Cooper! PR 잘 부탁드립니다.

테이블 설계, 예외 핸들링 부분을 중점적으로 봐주시면 감사하겠습니다!

### 구현 목록

---

- 로그인 기능(톰캣 세션저장소 사용)  
- 로그인 인터셉터 추가(리소스별 접근 권한)  
- 게시글 작성 시 작성자 세션 정보 사용  
- 유저 정보 수정 시 세션의 정보와 비교하여 예외 처리  
- 로그아웃 시 세션 삭제  

<br>

**로그인 전**
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/57752068/231986011-d4687a54-2fd1-4ed8-b367-22f837c6a365.png">

<br>

**로그인 후**
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/57752068/231986281-731a3010-1f05-4207-ab5d-69ff614a301a.png">

<br>

**글쓰기 폼**
<img width="946" alt="image" src="https://user-images.githubusercontent.com/57752068/231986460-2768389c-4e81-4f88-bfde-36c125fda7c5.png">

<br>

**개인 정보 수정 예외 페이지**
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/57752068/231989457-f33ed314-200f-4d36-846a-650fe18946bd.png">

### 고민

- 게시글을 조회할 때마다 작성자 정보 하나 때문에 Join을 하는 것이 비효율적이진 않은지 고민중입니다. 작성자 정보를 Article 테이블에 저장하고 유저가 아이디를 변경하면 해당 유저가 작성한 글을 일괄적으로 update 하면 Join을 하지 않아도 되는데 어색한 느낌이 드는 것 같습니다.

2023-04-14 17:11 UTC, pbg0205 requested changes
안녕하세요 빈 ~ 리뷰어 쿠퍼입니다. 3주간 좋은 코드에 대해 같이 고민해보시죠🔥🔥
중점적으로 봐주셨으면 하는 부분에 관해 검토해봤는데 게시판 미션에서 테이블 설게의 경우에는 설계에 관한 고민을 할 요소가 크게 없어서 어떤 피드백을 드려야 할지 잘 모르겠네요. 구체적으로 어떤 부분에 대해 피드백을 원하시는지 말씀해주시면 다시 한번 검토해보겠습니다 😃 리뷰에 관한 코멘트 확인 부탁드려요~

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/common/auth/LoginConfig.java
> +    }
URL 에 관한 인증 작업해주셨군요 👍👍

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/common/auth/LoginInterceptor.java
> +        if (hasNotLoginSession(session)) {
매서드 명은 일반적으로 긍정형으로 작성하는 것을 권장하고 있습니다~ 참고 부탁드려요
추가적인 학습을 위하신다면 클린 코드 책을 읽어보시는 것도 추천드립니다!
- https://wlgusdn700.tistory.com/87 (부정 조건을 피하라 검색)

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/common/auth/LoginInterceptor.java
> +        if (POST_METHOD.equals(request.getMethod())) {
스프링에서는 `org.springframework.http.HttpMethod` 패키지에서 `HttpMethod.POST` 를 지원해도 이걸로 대체하셔도 될 것 같아요

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/common/auth/LoginInterceptor.java
> +        final HttpSession session = request.getSession(false);
`session.setAttribute()` 대신 `request.getSession(false)` 을 사용하신 이유가 궁금합니다 🤔

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/common/exception/user/UserExceptionType.java
>  public enum UserExceptionType {
custom exception 과 ExceptionType 을 별도로 선언하신 의도가 궁금하네요 🤔

2023-04-14 17:11 UTC, pbg0205 commented on src/test/java/kr/codesqaud/cafe/service/UserServiceTest.java
> +import static org.assertj.core.api.Assertions.*;
* 대신 single import로 변경해주세요~

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/dto/article/ArticleCreateDto.java
> +        this.userFk = userFk;
변수명에 FK 에 관한 정보를 전달대신 id 로만 선언해줘도 될 것 같아요~

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/dto/article/ArticleCreateDto.java
>      }
사용하지 않는 코드는 제거해주세요~

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/dto/article/ArticleCreateDto.java
>              contents = "";
매직 스트링은 상수로 빼주세요~

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/dto/user/LoginUserSession.java
> +public class LoginUserSession {
도메인 객체 대신에 세션을 전용으로 담는 객체를 할당하는 장점은 무엇이 있을까요?

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/dto/user/LoginUserSession.java
> +    public boolean isNotSameUser(Long id) {
메서드는 긍정형으로 변경해주세요~

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/domain/Article.java
>      private String writer;
join 에 대한 성능 저하가 고민되신다면 반정규화에 관해 고민해보는 것도 좋을 것 같아요!
현재 코드에서 writer 를 선언하고 계신 것을 보아하니 이미 반정규화를 처리하신 것 같습니다~
(만약 아니라면 반정규 하셔도 좋을 것 같네요😃)

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/domain/Article.java
> +    private Long userFk;
이 부분도 userId 정도만 선언해도 좋을 것 같아요!

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/domain/User.java
>      }
사용하지 않는 코드는 제거해주세요~

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +                .ifPresent(m -> {throw new UserJoinException(UserExceptionType.DUPLICATED_EMAIL, userJoinDto);});
email 을 통한 검증 로직을 처리하는데 userId 로 조회하고 있어요 😢
추가적으로 id, email 모두 검증을 해야 하는지에 관한 의문이 있네요. 빈의 생각은 어떠신가요??

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +                .orElseThrow(() -> new CommonException(CommonExceptionType.NOT_FOUND_RESOURCE));
자원을 못찾는 경우를 모두 CommonException 으로 묶는 것이 가독성이 떨어질 수도 있지 않을까 하는 생각이 드네요.  특정 자원의 경우에 관한 예외 처리하면 가독성 측면에서 장점이 있지 않을까 해서 커스텀 예외에 관해 고민해보시는 것도 좋을 것 같습니다. (e.g. `UserNotFoundException`, 어디까지나 의견이므로 두 방법에 대한 장단점에 관해 고민해보시면 좋을 것 같아 코멘트 남깁니다 😃)

2023-04-14 17:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
>          if (user.isChangedUserId(userUpdateDto.getUserId())) {
로그인 시에 사용하는 id 는 일반적으로 변경하지 않지 않나요??

2023-04-15 09:43 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/common/auth/LoginInterceptor.java
> +        if (POST_METHOD.equals(request.getMethod())) {
헉 생각 못 했었는데 감사합니다!

2023-04-15 09:44 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/common/auth/LoginInterceptor.java
> +        if (hasNotLoginSession(session)) {
'!'를 사용하면 가독성이 떨어지는 것 같아서 Not을 붙였는데 처음부터 긍정형으로 작성하는 것이 좋겠군요. 클린 코드도 꼭 읽어보겠습니다. 감사합니다!

2023-04-15 09:48 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/common/auth/LoginInterceptor.java
> +        final HttpSession session = request.getSession(false);
session.setAttribute()는 로그인시에 사용하고 인터셉터에서는 세션에 저장된 로그인 정보가 있는지 확인하기 위해 request.getSession(false)를 사용했습니다. 혹시 질문해주신 부분이 이게 맞을까요..??

2023-04-15 10:12 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/common/exception/user/UserExceptionType.java
>  public enum UserExceptionType {
https://mangkyu.tistory.com/205
위의 블로그를 참고했는데 custom 예외가 너무 많아지는 것 같아서 범용적인 예외 클래스를 만들고 세부적인 예외 내용을 enum으로 관리하려고 했습니다..! 그런데 지금은 이도 저도(?) 아닌 것 같아서 수정을 하려고 고민중입니다 ㅠㅠ

2023-04-15 10:48 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/controller/dto/user/LoginUserSession.java
> +public class LoginUserSession {
세션이 was의 메모리에 저장이 되기 때문에 최소한의 정보만 담는 것이 메모리 관리에 효율적입니다. 그리고 서비스단 밖으로 도메인을 노출시키지 않는 이유도 있는 것 같습니다.

2023-04-15 10:59 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/domain/User.java
>      }
NamedParameterJdbcTemplate의 BeanPropertySqlParameterSource을 사용해서 내부적으로 getter가 사용되고 있는데 사용되지 않고 있다는 경고가 뜨네요..!

2023-04-15 11:15 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +                .ifPresent(m -> {throw new UserJoinException(UserExceptionType.DUPLICATED_EMAIL, userJoinDto);});
앗.. 이런 실수를 ㅠㅠ 얼른 고치겠습니다! 아이디와 이메일이 고유한 값이라 검증을 하긴 했는데 현재 이메일의 용도가 없으면 굳이 검증을 할 필요가 없을까요??

2023-04-15 11:31 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
>          if (user.isChangedUserId(userUpdateDto.getUserId())) {
로그인 아이디를 게시글 작성자로 사용하고 있어서 변경할 수 있도록 했는데 닉네임 같은 필드를 추가하는 것도 좋겠군요

2023-04-15 11:34 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +                .orElseThrow(() -> new CommonException(CommonExceptionType.NOT_FOUND_RESOURCE));
예외 처리를 다양하게 시도해보고 있는데 너무 묶으려고 하다 보니 가독성이 떨어지는 것 같습니다. 말씀해주신 부분 고민해보겠습니다 감사합니다!

2023-04-15 12:11 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/domain/Article.java
>      private String writer;
오오.. writer는 join을 해서 가져오고 있는데 반정규화 개념이 제가 고민하던 부분 같아서 한번 학습해보겠습니다 감사합니다!!

2023-04-15 12:14 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/controller/dto/article/ArticleCreateDto.java
> +        this.userFk = userFk;
저도 이 부분이 좀 고민이 되었는데요. Article에서 userId(FK)랑 User에서 userId(로그인 아이디)가 이름이 중복돼서 헷갈릴까봐 userFk로 했는데 userId로 사용해도 상관이 없을까요??

2023-04-15 12:20 UTC, tjdqls1200 commented
안녕하세요 @pbg0205  남겨주신 리뷰 보면서 많이 배웠습니다 ㅠㅠ 테이블 설계는 말씀해주신 반정규화에 대해 공부를 하고 고민을 해봐야 될 것 같습니다. 감사합니다!

2023-04-16 00:22 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/common/exception/user/UserExceptionType.java
>  public enum UserExceptionType {
공유주신 내용 읽어봤는데 이 부분은 선택의 영역인 것 같아요. 커스텀 예외를 사용하면 클래스나 인터페이스를 통해 예외 타입을 공통화 할 수 있는 장점이 있는 것 같고 해당 글에서는 내부 필드로 에외 타입을 선언하는 방식인 것 같아요. 만약에 인터페이스로 별도의 메서드를 정의할 필요가 없다면 이 방법도 괜찮을 것 같다는 생각이 드네요 😃 이번 미션에는 UserExceptionType 으로 활용해보시고 다른 미션에서는 한번 커스텀 예외를 사용해보셔서 어떤 방법이 더욱 빈한테 좋은 방법인지 기준을 가져가시면 될 것 같습니다 👍

2023-04-16 00:33 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/common/auth/LoginInterceptor.java
> +        final HttpSession session = request.getSession(false);
아 이 부부은 인증 부분을 처리하는 로직이었네요?? 로직을 보다가 순간 헷갈렸나봐요 😅 잘 작성해주셨습니다👍👍
혹시 네이밍을 인증을 처리하는 의미로 `AuthenticationInterceptor` 는 어떠세요?? 
(고려만 해주시고 더나은 방식으로 선택하시면 될 것 같습니다😄)

2023-04-16 00:35 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/dto/article/ArticleCreateDto.java
> +        this.userFk = userFk;
의미가 중복될 수 있다면 로그인 아이디를 변경하는 것이 좋을 것 같아요~ DB 에 대한 정보를 WAS 에서 까지 다룰 필요는 없는 것 같아요~ spring security 에서는 username 이라고 명명하는데 이 네이밍도 고려해보시면 좋을 것 같네요 😃

2023-04-16 00:37 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +                .ifPresent(m -> {throw new UserJoinException(UserExceptionType.DUPLICATED_EMAIL, userJoinDto);});
만약에 로그인하는 아이디로 이메일을 사용하지 않는다면 이메일은 유니크하지 않아도 되지 않을까 싶어요~

2023-04-16 00:49 UTC, pbg0205 approved these changes
우선 머지하고 다음 미션에 반영해주셔도 될 것 같아 `approve` 할게요 ~
코멘트에 답변드린 부분이 있는데 고민해보시고 빈이 더욱 적합한 방식으로 이후에 반영해주시면 될 것 같아요 👍 전반적으로 더 나은 방식에 대해서 고민하고 계셔서 덕분에 저도 같이 재밌게 리뷰했습니다
수고 많으셨으셨고 다음주에 뵐게요 ✋

2023-04-16 00:49 UTC, merged