[무비]  회원가입 및 회원 목록 조회 기능 + 글 쓰기 기능 구현
codesquad-members-2023/be-java-cafe-max pull request #18
Opened 2023-03-30 04:57 UTC by yhpark95

##  페어리뷰용 PR

2023-03-30 07:05 UTC, othertkfka commented on src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
> +}
WebMvcConfigurer 이렇게 사용하면 되는군요 저도 적용해보겠습니다.

2023-03-30 07:14 UTC, jsjseop reviewed
ArticleDto를 목적에 따라서 나눠주는 방법도 좋은 거 같은데
ArticleDetailDto와 ArticleListDto가 동일한 필드를 가진다면 통합해서 사용해도 될 거 같네요.
확장을 고려한다면 나눠줄 수 있겠지만 확장이 많이 되지 않을 거 같아요!

2023-04-01 14:02 UTC, wheejuni requested changes
수고하셨습니다. 🙇 몇 가지 의견 드립니다.

2023-04-01 14:02 UTC, wheejuni commented on src/main/java/kr/codesqaud/cafe/Controller/ArticleController.java
> +        model.addAttribute("articles", articleService.getArticleList());
이렇게 도메인 객체를 그대로 패스하는 것은 절대 비추입니다. (지금은 사용하지 않지만) JPA의 OSIV, 혹은 OEIV 개념을 알아보시고요, 이해가 되시면 좋지만 안 되셔도 상관 없습니다.
service layer에서 도메인 클래스의 사용이 멈추는 것이 안전한 구현인 것 같아요

2023-04-01 14:02 UTC, wheejuni commented on src/main/java/kr/codesqaud/cafe/Dto/ArticleDetailDto.java
> +    String contents;
공개 수준이 너무 넓은 것 같아요.

2023-04-01 14:02 UTC, wheejuni commented on src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
> +    private static long sequence = 0L;
이런 종류의 유즈케이스에 적합한, `long` 을 대체할만한 클래스도 한번 찾아보세요!

2023-04-01 14:02 UTC, wheejuni commented on src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
> +    }
제가 조금 이해가 어려운데요, `userId` 와 `userID` 가 다른 건가요?
만약 다르다면 변수 네이밍이 아쉽네요.

2023-04-03 01:52 UTC, yhpark95 commented on src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
> +    }
같은 건데 오해할 수도 있겠네요! 수정하겠습니다.

2023-04-03 01:56 UTC, yhpark95 commented on src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
> +    private static long sequence = 0L;
동시성 문제를 얘기해주시는 것 같은데 AtomicLong에 대해 학습을 하지 않아 일단 쓰지는 않았는데 해보도록 하겠습니다.

2023-04-03 01:57 UTC, yhpark95 commented on src/main/java/kr/codesqaud/cafe/Dto/ArticleDetailDto.java
> +    String contents;
private을 붙이는 걸 깜빡했네요.. 수정하겠습니다

2023-04-03 02:08 UTC, yhpark95 commented on src/main/java/kr/codesqaud/cafe/Controller/ArticleController.java
> +        model.addAttribute("articles", articleService.getArticleList());
도메인 객체를 그대로 패스하지는 않고 ArticleService에서 DTO로 필터링 후 반환해주고 있습니다, 근데 네이밍으로만 봤을때는 그렇게 오해할수 도 있겠네요. 네이밍에 좀 더 신경을 써야겠어요 감사합니다.

2023-04-04 05:11 UTC, merged