[bean] 댓글 기능
codesquad-members-2023/be-java-cafe-max pull request #233
Opened 2023-04-28 10:09 UTC by tjdqls1200

안녕하세요 Cooper! 마지막 PR 잘 부탁드립니다!

이번주는 댓글 기능(등록,수정,삭제,조회) API, 댓글 더보기 기능 구현을 했습니다. 

- 댓글 목록

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/57752068/235112789-7044c0a1-a73c-4e31-a791-6588e3db547d.png">
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/57752068/235113063-2d06b241-98c8-4e1c-a194-2511675280e3.png">
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/57752068/235113417-83a45c6b-6ee4-4589-8407-62b0f682409e.png">
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/57752068/235113565-aa7bd8ab-dcc5-4a6c-94d4-60e402a89833.png">

- 댓글 등록

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/57752068/235119066-be5c27b9-470e-478c-85a0-f6f25bef5ad5.png">
(다시 보니 userId, writer 정보는 서버 세션에서 꺼내야 되는데 자바스크립트에서 보내고 있네요..)

- 댓글 수정
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/57752068/235113775-0fb7510b-f310-4bdd-9726-b8066db46893.png">
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/57752068/235113897-4510d513-7b7e-491c-9204-84553f964901.png">
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/57752068/235114070-77ce4579-3611-457c-bd72-37a0c05d2f47.png">
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/57752068/235116807-b87386c2-676c-4e21-9db9-05fe8f455a49.png">

- 댓글 삭제
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/57752068/235114241-39f01793-3cb2-4a59-b6b8-d7f41cf8b54d.png">
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/57752068/235114353-62015673-d5af-4c4f-9991-2aedf00401ea.png">
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/57752068/235115845-0cb491c4-eb77-4442-b32f-6f2d25529d35.png">
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/57752068/235116519-e24fb024-ca25-47d6-8a5f-54674b3db3fb.png">

2023-04-29 07:11 UTC, pbg0205 requested changes
안녕하세요 빈~ 리뷰어 쿠퍼입니다 ✋ 벌써 마지막 PR 이네요ㅠ 마지막까지 화이팅 입니다 🔥🔥 
작업해주신 내용에 관해서 코멘트 드렸습니다~ 확인 부탁드려요!

2023-04-29 07:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
> +    public ApiResponse<Void> update(@PathVariable Long articleId, @PathVariable Long id, @RequestBody ReplyUpdateDto replyUpdateDto,
사용하지 않는 파라미터는 제거해주세요~

2023-04-29 07:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
> +    public ApiResponse<Void> delete(@PathVariable Long articleId, @PathVariable Long id,
사용하지 않는 파라미터는 제거해주세요~

2023-04-29 07:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
업데이트된 정보를 페이지에서 보여줘야 하는 경우에는 `status = 200` 을 전달하고 변경된 데이터를 전달하는 방법을 사용해도 될 것 같습니다.
(이 부분은 요구사항에 관련된 부분이니 빈 나름대로 정의해보시고 반영 여부를 검토해보시는 것도 좋을 것 같아요 😃)

2023-04-29 07:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/repository/JdbcReplyRepositoryImpl.java
> +
커서 페이지네이션을 구현해주셨군요 👍👍 커서 페이지네이션의 방식은 오프셋 페이지네이션와 비교했을 떄 장점은 무엇일까요?

2023-04-29 07:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/dto/ApiResponse.java
> +    private final boolean success;
성공, 실패를 구분은 전달할 수 있는 메세지가 적을 것 같아요. 조금 더 구체적인 메세지를 전달할 수 있는 방법을 고민해보시면 좋을 것 같습니다.😃

2023-04-29 07:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/dto/Pageable.java
> +public class Pageable {
추후에 Spring Data JPA을 학습하실 떄 Peageable 과 Slice 에 관해 학습해보시는 것도 좋을 것 같네요 👍

2023-04-29 07:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/common/auth/AuthConfig.java
> +                )
댓글 인증에 관련된 URL 이 없는 것 같아요~ 혹시 의도한 부분이시면 말씀 한번만 부탁드립니다😃

2023-04-29 07:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
> +                                    @SessionAttribute(LoginUserSession.KEY) LoginUserSession session) {
만약 SessionAttribute 가 null 일 경우에 예외가 발생할까요?? 만약 예외가 발생할 경우에는 어떤 예외를 던지는지에 관해서도 찾아보시면 좋을 것 같습니다 😃

2023-04-29 07:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
> +                                                 @RequestParam(required = false, defaultValue = "15") int size) {
defaultValue 가 존재하는 경우에도 `required  = false` 을 선언하신 의도에 대해서 말씀 부탁드려요~

2023-04-29 07:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
> +@RestController
`@RestController` 와 `@Controller` 의 차이는 무엇일까요??

2023-04-29 07:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/ReplyService.java
> +    }
클라이언트에서 잘못된 replyId 을 요청했을 경우에 ContollerAdvice를 통해 권한에 관련된 403 http status 를 반환해주게 되는데 이 부분은 좀 어색할 것 같네요. reply 를 조회 후에 로그인 사용자의 작성 글인지 확인한 후에 삭제하는 방식도 한번 검토해보시면 좋을 것 같습니다~ 쿼리가 늘어나더라도 서버에서의 응답이 명확해야 추후에 에러가 발생하더라도 원인을 제대로 파악할 수 있을 것 같아서요😃

2023-04-29 07:11 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/service/ReplyService.java
> +    }
요구사항이 추가됨에 따라서 로직이 복잡도가 증가되고 논리적 로직의 무결성과 일관성을 위해 트랜잭션에 관해서 학습해보시면 좋을 것 같습니다 😃

2023-04-30 13:18 UTC, pbg0205 approved these changes

2023-04-30 13:20 UTC, merged

2023-04-30 16:10 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
변경된 데이터를 전달하는 방법이 더 좋을 것 같은데 생각을 못했네요..! 감사합니다!

2023-04-30 16:13 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/repository/JdbcReplyRepositoryImpl.java
> +
오프셋 페이지네이션의 경우 오프셋 값이 커질 경우 실제 필요한 데이터에 비해 읽어들이는 데이터가 많아져서 효율성이 떨어지지만 커서 페이지네이션 방식은 시작 위치를 WHERE 조건으로 주기 때문에 속도가 훨씬 빠릅니다. 그리고 커서 페이지네이션 방식은 전체 페이지를 count할 필요가 없는 장점도 있습니다!

2023-04-30 16:17 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/controller/dto/ApiResponse.java
> +    private final boolean success;
상황에 따른 응답 코드를 별도로 전달해줘도 좋을 것 같은 생각이 들었습니다

2023-04-30 16:20 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/controller/dto/Pageable.java
> +public class Pageable {
이전에 Spring Data JPA를 학습해보면서 Slice를 살짝 사용해봐서 힌트를 얻었는데 이번에 다시 한번 학습해봐야겠습니다 감사합니다!

2023-04-30 16:32 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
> +                                    @SessionAttribute(LoginUserSession.KEY) LoginUserSession session) {
인터셉터에서 처리를 못해줘서 세션이 없는 경우 체크 예외인 ServletRequestBindingException이 발생하는데 찾아보니 치명적인 예외이군요..!

2023-04-30 16:35 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
> +                                                 @RequestParam(required = false, defaultValue = "15") int size) {
Request Parameter를 전달하지 않는 경우를 기본으로 허용하기 위해 required 옵션을 false로 했는데 그때의 값을 defaultValue로 선언했습니다. 다시 보니 required 옵션이 중복이네요 ㅠㅠ

2023-04-30 16:41 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
> +@RestController
`@RestController`는 `@Controller`에  `@ResponseBody`가 추가된 애노테이션입니다. 응답 데이터를 ResponseBody로 바로 반환하기 위해 사용하고 기본 `@Controller`의 경우 Viewname(또는 ModelAndView)을 반환해서 처리합니다.

2023-04-30 16:45 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/service/ReplyService.java
> +    }
삭제 기능의 경우 중요한 부분이기도 하고 자주 호출되는 로직이 아니다보니 명확하게 처리를 해주는 편이 좋겠군요. 감사합니다!

2023-04-30 16:59 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/service/ReplyService.java
> +    }
`@Transactional` 애노테이션을 아무 생각없이 붙이는 것 같아서 한번 더 학습을 하고 사용하려고 했는데요. 깊게 공부를 하려고 하니 아직 스프링 AOP에 대한 지식이 부족해서 이해가 어렵네요..ㅎㅎ 당장은 `@Transactional`을 사용해서 트랜잭션을 처리하는 코드를 서비스 로직에서 제거하고 AOP 사용시 주의점 정도만 학습을 했습니다.
지금은 기본적으로 autoCommit이 되고 있어서 서비스 로직이 복잡해지면 롤백을 해야 되는 상황에서 문제가 생길 것 같습니다.

2023-04-30 17:00 UTC, tjdqls1200 commented on src/main/java/kr/codesqaud/cafe/common/auth/AuthConfig.java
> +                )
앗.. 이 부분은 실수로 인터셉터 처리를 못 했네요 ㅠㅠ

2023-04-30 17:09 UTC, tjdqls1200 commented
급하게 구현을 하기도 했지만 실수한 부분이 많아서 앞으로 코드 리뷰 받게 되면 이런 부분을 조금 더 신경 써야겠네요 ㅠㅠ 3주간 깊게 생각해볼만한 질문이랑 키워드를 많이 주셔서 도움이 많이 됐습니다! 감사합니다!

2023-05-01 04:16 UTC, pbg0205 commented on src/main/java/kr/codesqaud/cafe/repository/JdbcReplyRepositoryImpl.java
> +
추가적으로 커서 페이지네이션을 구현할 때는 키값이 순서를 보장해줘야 하는 제약사항이 있습니다. UUID 를 PK로 사용하는 경우에는 id기준으로 페이지네이션이 어려우니 이점은 참고하시길 바래요✋