[Joy] 학습계획
codesquad-members-2023/be-java-cafe-max pull request #3
Opened 2023-03-27 06:56 UTC by he2joojo

2023-03-29 01:43 UTC, kyupid commented
안녕하세요 조이~ 이번 5주동안 리뷰 맡게된 큐라고 합니다
궁금한게 있는데 뒤에 xx분은 동영상 길이인가요~? 어떤거보고 학습하시는지 여쭤봐도 될까요?

2023-03-29 04:51 UTC, he2joojo commented
kyu 안녕하세요!! 
강의 동영상 길이 맞습니다~! 김영한님 강의 스프링 MVC1편 듣고있습니다!! :)

2023-03-30 07:09 UTC, pie2457 commented
서로 어려웠던 부분에 대해 의논하고, 생각해 보지 못했던 점을 이야기 하며 아주 화이팅 있는 시간을 보냈습니다 !
항상 학습계획 꼼꼼히 쓰시는 모습, 커밋 세세하게 하시는 부분까지!  꼭 배워가겠습니다 멋쨍ㅇ이 ☀️

2023-04-01 02:28 UTC, kyupid requested changes
안녕하세요 Joy🕺 첫 PR 고생 많으셨습니다. 👍

리뷰에 던진 질문들이 시간을 들여야하는 것들이 많을 것 같아요. 하실 수 있는 만큼 공부해보시고 기억해두었다가 다음에라도 다시 꼭 보시길 권장합니다. 다 중요한 것들이에요.

그리고 이번 주말에 join() 메소드는 꼭 리팩토링 해보시길 바랍니다. 일요일까지 기다리고 있을게요 이후에는 자동 merge 하겠습니다 😊

2023-04-01 02:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
> +//}
제 생각엔 개발할 때 뭐든지 "꼭" 사용해야하는 이유는 없을 것 같아요. 
아래 질문들을 생각해보시면 질문에 도움이 좀 될 것 같습니다.

- 스프링 부트와 스프링은 어떤 차이를 가지고 있을까요? 
- 스프링 부트에서 자동으로 구성해주는 것들은 무엇일까요?
- WebMvcConfigurer 를 구현하면 어떤 일을 할 수 있을까요?

2023-04-01 02:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    }
생성자가 하나만 있고, 그 생성자의 파라미터들이 모두 빈으로 등록되어 있으면 `@Autowired` 어노테이션 없이도 스프링이 자동으로 생성자를 통한 의존성 주입을 해줍니다. 따라서 해당 코드에서 `@Autowired`를 생략해도 의존성 주입이 정상적으로 이루어져요.

명확한 의도를 표현하기 위해 `@Autowired`를 사용하는 것도 좋은 방법이지만 코멘트 남기겠습니다.   
혹시 `@Autowired` 를 붙이면 무슨 일이 일어나는지 잘 모르신다면 꼭 먼저 공부해보세요. 😊

2023-04-01 02:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +
작성하신 다른 코드를 보면 개행하는 데에도 나름의 의미를 생각하신 것 같습니다. 이 부분도 깔끔하게 붙입시다 ㅎㅎ

2023-04-01 02:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    }
`@GetMapping("articles/{title}")` 이 조금 어색하게 느껴지네요. `title` 을 `@PathVariable` 로 받으신 이유가 궁금해요

2023-04-01 02:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +        User user = new User(form.getUserId(), form.getPassword(), form.getName(), form.getEmail());
지금은 괜찮지만 User 에 더 많은 필드가 있으면 생성자 파라미터가 굉장히 많고 헷갈릴거 같은데요. 다음엔 빌더 패턴도 한 번 고려해봅시다. 😊 

[참고 자료](https://johngrib.github.io/wiki/pattern/builder/#effective-java%EC%9D%98-%EB%B9%8C%EB%8D%94-%ED%8C%A8%ED%84%B4)

2023-04-01 02:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +                    throw new IllegalStateException("이미 존재하는 아이디입니다");
자바에서 다른 IllegalStateException 포함 다른 예외들은 어떻게 활용되고 있을까요? 

아래 표도 참고해보시고 한 번 조사해보세요 😊
![2023-04-01_11-01-03](https://user-images.githubusercontent.com/59721293/229260550-b290f698-689d-4bd9-81ab-1a860e8e8532.jpg)

2023-04-01 02:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +        userRepository.findById(user.getUserId())
아래 `findOne(String userId)` 와 비슷한 기능을 하는 것 같아요. 합쳐서 사용해볼 순 없을까요?

2023-04-01 02:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +            return " ";
세 가지 의견이 있습니다.

1. `" "` 라는 표현을 사용하고 싶으셨다면 주석으로 의미를 전달하는 것도 좋지만 변수에 이름을 붙여서 좀 더 명확하게 표현해야 바람직할 것 같습니다. 그리고 불변이면 더 좋겠죠.  왜 그럴까요?
2. join 메소드에서 try-catch 문이 필요해보이진 않습니다. 동시에 `" "`와 같은 상수도 불필요해 보입니다. 개선해볼 수 없을까요?
3. IllegalStateException 은 try-catch 로 감싸지 않아도 되는 Exception 입니다. Checked Exception 과 Unchecked Exception 에 대해 공부해보세요.

2023-04-01 02:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +            return "redirect:/users";    // 정상가입되었다면, 회원목록 창으로
해당 코드는 UserService 에 대한 리뷰를 참고해주세요.

2023-04-01 02:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/dto/UserForm.java
> +    }
이 클래스의 setter 들은 언제 사용하는 것인가요?

2023-04-01 02:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
> +    private Map<String, Article> articleStore = new ConcurrentHashMap<>(); // 제목:Article 저장
HashMap 이 아니라 ConcurrentHashMap 을 사용하신 이유가 무엇인가요?

2023-04-01 02:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
> +        return new ArrayList<>(articleStore.values());
그냥 articleStore 을 반환하면 안될까요? 꼭 새로운 List 로 반환해야하나요? 어떤 이유로 이렇게 작성하셨을까요?

2023-04-01 03:21 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
> +//}
참고로 위 코멘트는 조이가 남겨둔 고민에 대한 답변입니다.

```
 WebMvcConfigurer를 구현한 MvcConfig클래스를 꼭 사용해야 하는 이유를 아직 몰라 주석으로 처리해두었습니다.
```

2023-04-02 12:41 UTC, merged

2023-04-02 13:20 UTC, he2joojo commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    }
'@Autowired'가 생략 가능한 경우가 있다는 걸 잊고있었네요!! 수정했습니다 😃

2023-04-02 13:33 UTC, he2joojo commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    }
동일한 작성자가 글을 여러개 작성한 경우가 있다고 생각해서, title를 ```@PathVariable``` 로 받았습니다!! 이후에 같은 글 제목을 두개 이상 생성할 수 없게 로직을 추가할 생각이었는데, 다시 보니 제가 봐도 조금 어색한 것 같네요... ```@ PathVariable```로 뭘 받으면 좋을 지 더 생각해보겠습니다!

2023-04-02 14:44 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    }
> 같은 글 제목을 두개 이상 생성할 수 없게

동일한 작성자가 글을 여러개 작성한다는 게 작성자가 두 번이상 요청하는 것을 방지하기 위함인가요?

2023-04-03 02:14 UTC, he2joojo commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    }
동일한 작성자가 글을 여러개 쓰는 것은 가능한데, 제목이 같은 글은 하나만 작성할 수 있습니다! 
> 동일한 작성자가 글을 여러개 작성한 경우
<img width="1470" alt="스크린샷 2023-04-03 오전 11 09 42" src="https://user-images.githubusercontent.com/121915790/229396166-cbd31d49-52f4-4013-8795-cb741014dd28.png">
> 이미 존재하는 글과 같은 제목으로 글을 작성시 에러 발생
<img width="1470" alt="스크린샷 2023-04-03 오전 11 11 13" src="https://user-images.githubusercontent.com/121915790/229396242-27c791e5-0508-46a3-bb07-5b6e37cf371b.png">

처음에 @GetMapping("articles/{userId}")로 userId를 @PathVariable 로 받아서 작성 글을 보여주려고 했는데, 한 작성자가 글을 여러개 작성하면 url이 중복돼서 어떤 글을 보여줘야 할 지 모호해 진다는 문제가 생겼습니다. <br>

그래서 title 을 @PathVariable 로 받고, 대신 같은 제목을 두개 이상 생성할 수 없게해서 url이 중복되는 문제를 해결하려 했습니다!!

2023-04-03 07:48 UTC, he2joojo commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +        User user = new User(form.getUserId(), form.getPassword(), form.getName(), form.getEmail());
좋은자료 감사합니다! 빌더패턴이 뭔지 이해했습니다!!😃

2023-04-03 08:11 UTC, he2joojo commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +            return " ";
그룹리뷰에서 예외를 try-catch로 처리하지 말고 ```@Controlleradvice```로 다뤄보라는 피드백을 받아 공부중인데 아직은 너무 어려워  일단 UserService의 join메서드를 ```public boolean join(User user) {
       if (findOne(user.getUserId()).isPresent()) {
           return false;
       }
       userRepository.save(user);
       return true;
    }``` 로 임시 변경했습니다!! 좋은 피드백 감사합니다!:)

2023-04-03 08:13 UTC, he2joojo commented on src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
> +    private Map<String, Article> articleStore = new ConcurrentHashMap<>(); // 제목:Article 저장
웹사이트라서 동시성 문제가 생길 수 있다고 생각해서 ConcurrentHashMap을 사용했습니다 :)

2023-04-03 08:17 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    }
의도는 이해했습니다. Article 에 Id 필드를 하나 추가해주면 어떨까요?

2023-04-03 08:17 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +        User user = new User(form.getUserId(), form.getPassword(), form.getName(), form.getEmail());
벌써 이해하셨다니 최곱니다👍

2023-04-03 08:22 UTC, he2joojo commented on src/main/java/kr/codesqaud/cafe/dto/UserForm.java
> +    }
setter들을 삭제하면 회원가입시 에러가 발생해서 모두 살려놨습니다! 왜 에러가 발생하는지는 스프링을 더 공부해봐야 알 것 같습니다🥹

2023-04-03 08:35 UTC, he2joojo commented on src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
> +        return new ArrayList<>(articleStore.values());
articleStore를 그대로 반환하면 MemoryArticleRepository와 ArticleService클래스 사이의 결합도가 높아질 것 같아서 새로운 List로 만들어 반환했습니다!

2023-04-03 09:28 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/dto/UserForm.java
> +    }
타임리프에서 setter 를 사용하는거였군요 ㅠㅠ 제가 잘 몰랐습니다.

2023-04-03 09:38 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
> +        return new ArrayList<>(articleStore.values());
결합도가 높다는 게 어떤 의미인가요? 🤔  Repository 에 있는 필드를 Service 에서 사용하면 문제가 생기나요? 그렇게 치면 service 에서 repository 메소드를 사용하는 것도 결합도가 높아서 사용하면 안되지 않을까요?

2023-04-03 11:36 UTC, he2joojo commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    }
그런 방법이 있었네요!! title을 ```@PathVariable```로 받는게 계속 걸렸는데 감사합니다🥺

2023-04-03 12:23 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/service/UserService.java
> +            return " ";
ControllerAdvice 어노테이션 배워서 사용하는 것도 좋구요. 개인적으론 지금처럼 날것으로 어떻게 해야 문제를 풀 수 있을지 고민하는게 더 성장에 도움 될거같아요. 잘하셨습니다 👏

2023-04-03 12:24 UTC, kyupid commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    }
많이 고민하신 흔적이 보이네요. 지금처럼 화이팅입니다💪