[브루니] 중복된 HTML 분리 / 회원 가입, 프로필 수정, 회원 목록 조회, 회원 프로필 조회기능 / 게시글 포스팅, 게시글 목록 조회, 게시글 상세내용 조회
codesquad-members-2023/be-java-cafe-max pull request #35
Opened 2023-03-31 08:44 UTC by 23Yong

## 주요 작업
* [x] 중복된 HTML 분리
  * header / footer / navigationbar 파일로 분리
* [x] 서버사이드 렌더링을 위한 `mustache` 템플릿 엔진 추가
  * `/static` 폴더에 있던 .html 파일들은 `/templates` 폴더로 이동
* 회원 (User)
  * [x] 회원 가입 기능 구현
  * [x] 회원 전체 조회 기능 구현
  * [x] 회원 프로필 조회 기능 구현
  * [x] 회원 프로필 수정 기능 구현 
  * [x] `UserService` 클래스 테스트코드 작성
* 게시글 (Article)
  * [x] 게시글 생성 기능 구현
  * [x] 게시글 전체 조회 기능 구현
  * [x] 게시글 상세 내용 조회 기능 구현
  * [x] `ArticleService` 클래스 테스트코드 작성

## 학습 키워드
* HTTP GET / POST
* @ ModelAttribute
* @ ControllerAdivce
* @ Configuration(proxyBeanMethods = false)

## 고민과 해결
* `User`, `Article` 클래스(도메인)가 `Controller` 레이어, `Service` 레이어에서 사용되면 상태를 변경시키거나 뷰를 그리기 위한 필요없는 정보(비밀번호)가 있어 이를 해결하기 위해 `DTO`를 사용했습니다.
* 예외처리를 한 곳에서 하기 위해 `@ControllerAdvice` 를 사용해 예외를 한 클래스에서 처리하도록 했습니다.
* 애플리케이션에서 발생할 수 있는 예외를 커스터마이징하기 위해 사용자 정의 예외를 생성했습니다.
  * 예외의 종류가 많아지면 관리해야할 클래스 파일의 개수가 늘어날 것 같습니다.

## 동작화면
<details>
<summary>회원가입 페이지</summary>

![image](https://user-images.githubusercontent.com/66981851/228137723-e7bdd013-fa9e-4d8e-afbd-487a21afeca3.png)
</details>

<details>
<summary>중복된 아이디를 입력했을 때</summary>

![image](https://user-images.githubusercontent.com/66981851/228137859-7bb46d44-4dfc-42a1-afd0-b715429bd5fd.png)
</details>

<details>
<summary>회원 목록 화면</summary>

![image](https://user-images.githubusercontent.com/66981851/228138025-8a2c1a3b-d54c-498f-80a2-428ba14574c6.png)
</details>

<details>
<summary>회원 프로필 화면</summary>

![image](https://user-images.githubusercontent.com/66981851/228138110-a614316d-6976-468a-a27b-9f1f94ab71db.png)
</details>

<details>
<summary>존재하지 않는 회원 아이디를 url에 담아 접근했을 때</summary>

![image](https://user-images.githubusercontent.com/66981851/228141390-ac8362ca-2803-460f-8b64-c85a27b052cd.png)
</details>

<details>
<summary>글 목록 화면</summary>

![image](https://user-images.githubusercontent.com/66981851/228710067-253acca0-6996-4ed7-858a-aa59cf8d1a3d.png)
</details>

<details>
<summary>글 상세 화면</summary>

![image](https://user-images.githubusercontent.com/66981851/228710494-ec317a64-22b9-475a-99af-b24e42b28428.png)
</details>

<details>
<summary>회원 정보 수정시 기존 비밀번호와 일치하지 않을 때</summary>

![image](https://user-images.githubusercontent.com/66981851/228710272-1503a359-fd39-41da-9729-01d1f848939c.png)
</details>

2023-04-01 14:17 UTC, wheejuni requested changes
수고 많으셨습니다. 👍 
몇 가지 의견 드릴게요.

2023-04-01 14:17 UTC, wheejuni commented on src/main/java/kr/codesqaud/cafe/controller/dto/UserDto.java
> +	private final Long rowIndex;
`rowIndex` 라는 표현이 애매합니다. 테이블 내에서 index를 표시하기 위한 칼럼일까요?
그렇다면 일단 데이터가 내려가면 FE가 해결해야 할 부분인데, 이걸 BE 로직에 섞는게 좀 이상해 보입니다.

2023-04-01 14:17 UTC, wheejuni commented on src/main/java/kr/codesqaud/cafe/controller/dto/req/ProfileEditRequest.java
> +	private final String oriPassword;
`ori` 는 잘 쓰지 않는 표현인데요, `original` 로 끝까지 써주시는 것이 어떨까요?

2023-04-01 14:17 UTC, wheejuni commented on src/main/java/kr/codesqaud/cafe/exception/DuplicatedUserIdException.java
> +public class DuplicatedUserIdException extends RuntimeException {
굉장히 구체적인 케이스에 사용될 예외를 작성해 주셨는데, message도 이 클래스에서 관리하고 제공하면 어떨까 하는 생각은 듭니다.

2023-04-01 14:17 UTC, wheejuni commented on src/main/java/kr/codesqaud/cafe/repository/impl/UserMemoryRepository.java
> +		return Optional.of(user);
질문 있습니다.
- `HashMap` 에서 기존에 있는 키를 다시 한번 사용해서 `.put()` 하는 경우 어떤 일이 일어날까요?

2023-04-02 04:03 UTC, 23Yong commented on src/main/java/kr/codesqaud/cafe/controller/dto/UserDto.java
> +	private final Long rowIndex;
감사합니다! 테이블의 인덱스를 표현하는 것은 프론트에서 해결해보도록 수정하겠습니다.

2023-04-02 04:03 UTC, 23Yong commented on src/main/java/kr/codesqaud/cafe/controller/dto/req/ProfileEditRequest.java
> +	private final String oriPassword;
넵! 수정하겠습니다👍

2023-04-02 04:04 UTC, 23Yong commented on src/main/java/kr/codesqaud/cafe/exception/DuplicatedUserIdException.java
> +public class DuplicatedUserIdException extends RuntimeException {
의견 감사합니다! 말씀대로 예외 메시지를 예외 클래스에서 관리하도록 하겠습니다.

2023-04-02 04:09 UTC, 23Yong commented on src/main/java/kr/codesqaud/cafe/repository/impl/UserMemoryRepository.java
> +		return Optional.of(user);
중복된 키가 입력될 경우 기존에 있는 요소가 대체됩니다!

아래 테스트를 통해 직접 확인해보았습니다.
```java
@Test
void hashMapTest() {
	Map<String, String> map = new HashMap<>();
	map.put("key", "value1");
	map.put("key", "value2");
	assertThat(map.get("key")).isEqualTo("value2");
}
```

2023-04-04 05:11 UTC, merged