[나그] step -1 구현
codesquad-members-2023/be-java-cafe-max pull request #39
Opened 2023-03-31 08:55 UTC by n-aa-g

안녕하세요. Sigrid. 나그입니다.
앞으로 5주 동안 제 코드를 리뷰해 주실텐데 잘 부탁드립니다.
다만 먼저 설명 드리기 전에 코드가 더럽다는 이야기를 말씀드리고 싶습니다.
오늘 갑자기 편도가 심하게 부어 많은 작업을 하지 못했고 제가 계획했던 리팩토링 작업을 하지 못했습니다.
다음 주부터는 컨디션을 관리하여 좀 더 깔끔한 코드와 설명을 작성하겠습니다.

### 이번 주의 학습 방향
저는 이번 주에 처음 스프링을 접했습니다. 그래서 '많은 것을 깊게 학습하겠다'는 마음보다는 '알단 구현을 해보자'라는 방향을 세웠습니다.
다른 블로그에 있는 예제 코드를 보고 어떻게 작동하는 지를 피상적으로 생각해보았고 이를 적용하여 코드를 작성했습니다.

### 구현 기능 목록
- 아이디, 패스워드, 이름, 이메일을 입력받아 회원 가입
- 회원 가입한 전체 회원들의 출력
- 각 회원의 프로필 보기

### 학습한 키워드
어노테이션, 타임 리프

2023-03-31 09:54 UTC, sigridjineth commented
나그님 안녕하세요? 저는 시그리드입니다. 앞으로 5주 동안 함께할 시간이 기대됩니다.

먼저 당부할 사항을 드리면:
• 언제든 코드리뷰 요청을 주셔도 좋습니다. 마치 숙제 제출하는 것처럼 완료가 되었다고 생각했을 때 리뷰 요청을 주실 필요는 없고 기능 단위로 리뷰 요청을 주셔도 좋습니다.
• 제가 일정 상 바로바로 리뷰를 봐드릴 수는 없지만 48시간(2일) 이내에 리뷰를 완료할 수 있도록 노력하겠습니다.
• 궁금하신 점이 있으시면 별도로 DM을 남겨주시면 감사드리겠습니다.

더러운 코드라는 것은 정해져 있는 기준이 있지 않고 본인이 남들에게 설명할 수 있고 왜? 라는 질문에 답할 수 있다면 그 사람에게 있어서는 최선의 코드라고 생각합니다.

마지막으로, 학습 기간 중 건강과 행복을 최우선으로 하시기를 당부드립니다. 리뷰는 주말 중 확인하고 답신드리겠습니다.

감사합니다!

2023-03-31 10:11 UTC, realsigridjin requested changes

2023-03-31 10:11 UTC, realsigridjin commented on src/main/java/kr/codesqaud/cafe/user/UserService.java
> +        user.setEmail(userForm.getEmail());
유저 아이디부터 이메일 설정까지 사용자를 등록한다고 하는 하나의 행위로 묶을 수 있을 것입니다. 그렇다면 행위 단위로서 관리를 해볼 수 있지 않을까요?

2023-03-31 10:11 UTC, realsigridjin commented on src/main/java/kr/codesqaud/cafe/user/UserRepository.java
> +    public List<User> getRepository() {
`getRepository` 라는 변수명은 `HashMap` 자체를 반환하는 것으로 들리는데요. 실제로는 `HashMap`에 담겨있는 `User` 아이템들을 `values`로 반환하고 있습니다. 변수명이 예상되는 것과 다르게 들리는 것 같아요.

어떻게 개선할 수 있을까요?

2023-03-31 10:11 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/user/UserRepository.java
> +        repository.put(user.getUserId(), user);
만약 `userId`가 중복으로 겹치게 된다면 어떤 일이 일어날까요? 예를 들어, `sigridjineth` 라는 닉네임이 key로 이미 존재하는데 같은 key를 가진 `User` 객체를 중복으로 넣는 상황이죠.

2023-03-31 10:11 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/user/UserForm.java
> +        this.password = password;
일반적으로 비밀번호를 평문으로 저장하면 보안상 여러 문제점이 있다고 합니다. 어떻게 개선할 수 있을까요?

2023-03-31 10:11 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/user/UserController.java
> +    public String findByUserId(@PathVariable("userId") String userId, Model model) {
API 명세를 작성할 때 query string과 path parameter 중 본인이 선호하거나 선택하는데 고려하는 기준이 무엇인지 궁금합니다. 이와 더불어 `@PathVariables` 가 어떤 어노테이션이라 생각하시는지 간단하게 정리해서 답신을 주세요!

2023-03-31 10:11 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/user/UserRepository.java
> +    public User fineByUserId(String userId) {
오타가 있습니다. `findByUserId`

2023-03-31 10:11 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/user/UserService.java
> +        User user = new User();
생성자 주입이라는 개념에 대해 들어보셨나요?

2023-03-31 10:11 UTC, sigridjineth commented on src/main/resources/templates/index.html
> +<script src="../static/js/scripts.js"></script>
자바 백엔드 과정에서 중점적으로 다루는 내용은 아니지만, 프론트엔드 지식을 기본적으로 숙지하고 있는 것은 매우 중요한 사항입니다.

과거의 서버 사이드 렌더링과 요즘의 SPA 방식 및 클라이언트 사이드 렌더링, 그리고 이 패러다임에 맞는 라이브러리 (jQuery, React, Svelte) 각각이 어떤 특징이 있는 지 간단하게 정리해서 답신을 보내주세요.

2023-03-31 10:11 UTC, sigridjineth commented on src/test/java/kr/codesqaud/cafe/UserRepositoryTest.java
> +        Assertions.assertThat(userRepository.getRepository()).contains(user);
여기서 `getRepository` 메소드를 사전에 호출해서 검증하는 로직만 해당 라인에서 표시될 수 있도록 하는 것이 좋다고 생각합니다.

2023-03-31 10:11 UTC, sigridjineth commented on src/test/java/kr/codesqaud/cafe/UserRepositoryTest.java
> +        Assertions.assertThat(userRepository.getRepository()).contains(user);
다음의 차이는 무엇일 지 생각해보세요.

```
Assertions.assertThat(userRepository)...

assertThat(userRepository)...
```

2023-04-02 21:52 UTC, sigridjineth approved these changes

2023-04-02 23:19 UTC, merged

2023-04-07 08:10 UTC, n-aa-g commented on src/main/resources/templates/index.html
> +<script src="../static/js/scripts.js"></script>
SSR(Server Side Rendering)을 간단하게 말하지면 서버가 페이지를 만드는 것입니다. 지금 제가 웹 페이지를 만드는 방식입니다. 
CSR(Client Side Rendering)은 서버에서 전체 페이지를 한번 만들어 주고, 변경이 일어나는 부분의 데이터를 서버에서 받아 렌더링하는 방식입니다.
SPA(Single Page Application)은 하나의 페이지로 이루어져 있는 어플리케이션으로 CSR을 사용하여 렌더링합니다.
MPA(Multiple Page Application)은 여러 개의 페이지로 이루어져있는 어플리케이션으로 SSR을 사용하여 렌더링합니다.

제가 지금 만드는 카페는 MPA방식입니다. 요청이 들어올 때마다 새로운 페이지를 만들고 띄웁니다. 따라서 요청이 작아 작은 부분만 수정하면 되는 경우에도 페이지를 새로 띄워야 하는 비효율적인 문제가 발생합니다. 반면에 SPA방식에서는 전체 페이지를 로딩하는데 시간이 걸리지만 부분만을 수정하기에 효율적입니다.

제이쿼리는 오픈소스 자바스크립트 라이브러리로 리액트 전까지 대세였던 기술이였습니다. 
리액트는 가상 돔을 활용한 자바스크립트 라이브러리입니다. 페이스북에서 개발한 것으로 유명한 라이브러리이죠. 리액트의 핵심은 가상 돔을 쓴다는 것같습니다. 돔의 구조를 전체적으로 바꿔서 렌더링을 새로 하는 것이 아니라, 가상 돔을 사용하여 돔의 일부분만 바꾼다는 것이 중요한 것같습니다.
스벨트는 런타임이 아니라 빌드 타임에 코드를 해석하기에 리액트보다 뛰어난 성능을 보입니다. 또한 리액트와 다르게 가상 DOM기술을 쓰지 않습니다.

2023-04-07 08:10 UTC, n-aa-g commented on src/test/java/kr/codesqaud/cafe/UserRepositoryTest.java
> +        Assertions.assertThat(userRepository.getRepository()).contains(user);
넵 새로 변수를 만들어 수정했습니다!

2023-04-07 08:15 UTC, n-aa-g commented on src/test/java/kr/codesqaud/cafe/UserRepositoryTest.java
> +        Assertions.assertThat(userRepository.getRepository()).contains(user);
위의 방법은 Assertions 클래스의 static 메서드인 assertThat를 호출하는 것입니다.
아랫줄은 Assertions 클래스를 import static하여 메서드만 바로 사용하는 것입니다.

윗줄보다 아랫줄이 낫다고 생각합니다.
코드가 문장으로 읽히는게 좋다고 생각하는데, 윗줄에는 클래스이름이 끼어있어 하나의 문장으로 읽히지 않습니다.
아랫줄은 '나는 확신한다 ~ 를'이런 구조로 읽히기 때문에 가독성 측면에서 더 낫다고 생각합니다.
그리고 코드에 반영했습니다.

2023-04-07 08:17 UTC, n-aa-g commented on src/main/java/kr/codesqaud/cafe/user/UserRepository.java
> +    public User fineByUserId(String userId) {
넵 수정했습니다.

2023-04-07 08:27 UTC, n-aa-g commented on src/main/java/kr/codesqaud/cafe/user/UserRepository.java
> +        repository.put(user.getUserId(), user);
레퍼지토리를 HashMap으로 구현했기에 같은 key를 가진 다른 객체가 들어오면 변경됩니다.
결국 먼저 등록한 회원은 레퍼지토리에서 자동적으로 없어질 것입니다.
이에 대해서 레퍼지토리에서 id를 부여하여 map의  key로  id를 사용하면 될 것 같습니다.

2023-04-07 08:47 UTC, n-aa-g commented on src/main/java/kr/codesqaud/cafe/user/UserRepository.java
> +    public List<User> getRepository() {
getAllUsers라는 이름으로 좀 더 의미가 잘 전달되게 했습니다.

2023-04-07 08:48 UTC, n-aa-g commented on src/main/java/kr/codesqaud/cafe/user/UserService.java
> +        user.setEmail(userForm.getEmail());
도메인을 set으로 변경되는게 보안상 좋지 않다고 생각했습니다.
그래서 생성자를 통해서 user를 만들고 레퍼지토리에 넣었습니다.

2023-04-20 02:03 UTC, n-aa-g commented on src/main/java/kr/codesqaud/cafe/user/UserForm.java
> +        this.password = password;
저라면 uilt패키지를 새로 만을고 그 안에 암호화관련 클래스를 하나 만들 것 같습니다. 
AES 256 써서 암호화, 복호화 클래스를 만들 것 같습니다.
그리고 메서드는 static으로 선언해서 Service에서 쓸 수 있게 할 것같습니다.
dto를 컨트롤러에서 서비스로 넘겨주고 서비스에서 domain을 만들어서 레포티토리에 남겨주는데, dto를 domain에서 만드는 과정에서 암호화하는 게 맞다고 생각했기 때문입니다.

2023-04-20 02:13 UTC, n-aa-g commented on src/main/java/kr/codesqaud/cafe/user/UserController.java
> +    public String findByUserId(@PathVariable("userId") String userId, Model model) {
먼저 저 url은 생각이 없었습니다. 미션 요구사항에 있어서 그대로 쓴거였습니다.
하지만 시그리드께서 url을 만드는 다른 방식인 query string에 관해서 알려주셨고 알아봤습니다.
path parameter는 리소스를 식별할 떄 쓰는 것이라고 나와있고, 
query string은 리소스들을 정렬하고 필터링 할 떄 쓰는 것이라고 봤습니다.
바꿔 말하면 path parameter의 값들은 리소스의 고유한 값이 들어가야 하고 query string에는 정렬 기준이 들어가야 한다고 생각합니다.
따라서 이 메서드의 기능이 특정 user를 식별하고 user 정보를 가지고 오는 것이기에 path parameter를 쓰는 것이 맞다고 생각합니다.

또한 @PathVariable은 URL에서 추출한 값을 매개변수로 쓸 수 있게 해주는 어노테이션입니다.
이 경우 url 의 userId가 String userId로 변환되어서 메서드에서 쑬 수 있습니다.

2023-04-20 02:35 UTC, n-aa-g commented on src/main/java/kr/codesqaud/cafe/user/UserService.java
> +        User user = new User();
넵 제가 필드 주입을 사용하고 있었는데, 이번에 다양한 주입 방식이 있고 이번 미션의 경우 생성자 주입이 가장 좋다고 판단해서 생성자 주입으로 변경했습니다.
생성자 주입과 비교했을 때 필드 주입은 테스트 하기 어렵고 스프링코드가 코드내에 침투하는 등의 문제가 있어 생성자 주입을 사용했습니다.