[위즈] 스프링 카페 미션 - step-1, 2 구현
codesquad-members-2023/be-java-cafe-max pull request #42
Opened 2023-03-31 08:58 UTC by Jeongwisdom

안녕하세요, 위즈입니다. 제가 중간에 코드를 처음부터 새로 작성해서 커밋 내용은 [스프링 카페1 1단계 회원가입 기능 새로 구현]부터 봐주시면 감사하겠습니다!!

## 기능 구현
- 회원 가입 기능 구현
![2](https://user-images.githubusercontent.com/108439935/229055712-d78ee0cf-582a-4e0b-88cc-f76b6f9357e3.png)

- 회원 목록 조회 기능 구현
![3](https://user-images.githubusercontent.com/108439935/229055808-107ecaa6-6e76-4456-94a9-ab942b3b8ddf.png)

- 회원 프로필 조회 기능 구현
![4](https://user-images.githubusercontent.com/108439935/229055867-85bd1180-9c3c-4f02-bc02-22130c68cbcb.png)

- 글 쓰기 기능 구현
![5](https://user-images.githubusercontent.com/108439935/229055970-0ffd0577-09af-4139-a975-b34baf2a3451.png)

- 글 목록 조회 기능 구현
![6](https://user-images.githubusercontent.com/108439935/229056023-32d91b18-b4c3-44dc-97f7-36a3f2211792.png)

- 게시글 상세 보기 기능 구현
![9](https://user-images.githubusercontent.com/108439935/229056348-c023e3cf-3325-4d7f-9204-329a76c1132e.png)

- 사용자 정보 수정 기능 구현
![7](https://user-images.githubusercontent.com/108439935/229056110-06d42b5e-f619-4c0c-b939-edaa82473eae.png)
![8](https://user-images.githubusercontent.com/108439935/229056138-07c21f09-6447-4e70-92f2-8ad9b87d72cb.png)
wis의 닉네임이 wiswis로 수정된 것을 확인할 수 있습니다.

## 궁금한 내용
- html 내용이라 질문해도 될지 모르겠지만 html 중복 내용을 header로 빼냈는데 <body>태그도 포함되어도 상관없는지 title 내용만 각각마다 바꿔주고 싶을 때 document.querySelector를 이용해서 그 부분만 바꿔줘도 괜찮은지 궁금합니다.

## 리팩토링해야할 부분
- 저번주 자바스크립트를 이용해서 회원가입 폼에 예외처리를 해주었는데 스프링으로 하면서 두 부분을 연결하지 못했습니다. 예외 처리하는 부분을 공부해서 예외처리해줄 필요가 있습니다. -> 추가 공부: exceptionHandler, ControllerAdvice
- 스쿼드 세션의 피드백
  - service 부분을 만들어서 repository에서 dto나 user 클래스를 처리하는 것을 service의 책임으로 만들어줘야 할 것 같습니다.
  - UserFormRepository의 userList를 concurrentHashMap으로 바꾼 후 user의 index를 hashMap의 key값으로 넣어 리팩토링하면 좋을 것 같습니다.

읽어주셔서 감사합니다:) 행복한 하루 보내시길 바랍니다!!

2023-04-01 11:12 UTC, sigridjineth commented
위즈님 안녕하세요? 저는 시그리드입니다. 앞으로 5주 동안 함께할 시간이 기대됩니다.

먼저 당부할 사항을 드리면:
• 언제든 코드리뷰 요청을 주셔도 좋습니다. 마치 숙제 제출하는 것처럼 완료가 되었다고 생각했을 때 리뷰 요청을 주실 필요는 없고 기능 단위로 리뷰 요청을 주셔도 좋습니다.
• 제가 일정 상 바로바로 리뷰를 봐드릴 수는 없지만 48시간(2일) 이내에 리뷰를 완료할 수 있도록 노력하겠습니다.
• 궁금하신 점이 있으시면 별도로 DM을 남겨주시면 감사드리겠습니다.

더러운 코드라는 것은 정해져 있는 기준이 있지 않고 본인이 남들에게 설명할 수 있고 왜? 라는 질문에 답할 수 있다면 그 사람에게 있어서는 최선의 코드라고 생각합니다.

마지막으로, 학습 기간 중 건강과 행복을 최우선으로 하시기를 당부드립니다.

감사합니다!

2023-04-01 11:13 UTC, sigridjineth commented
위즈님 안녕하세요? 저는 시그리드입니다. 앞으로 5주 동안 함께할 시간이 기대됩니다.

먼저 당부할 사항을 드리면:
• 언제든 코드리뷰 요청을 주셔도 좋습니다. 마치 숙제 제출하는 것처럼 완료가 되었다고 생각했을 때 리뷰 요청을 주실 필요는 없고 기능 단위로 리뷰 요청을 주셔도 좋습니다.
• 제가 일정 상 바로바로 리뷰를 봐드릴 수는 없지만 48시간(2일) 이내에 리뷰를 완료할 수 있도록 노력하겠습니다.
• 궁금하신 점이 있으시면 별도로 DM을 남겨주시면 감사드리겠습니다.

더러운 코드라는 것은 정해져 있는 기준이 있지 않고 본인이 남들에게 설명할 수 있고 왜? 라는 질문에 답할 수 있다면 그 사람에게 있어서는 최선의 코드라고 생각합니다.

마지막으로, 학습 기간 중 건강과 행복을 최우선으로 하시기를 당부드립니다.

감사합니다!

2023-04-01 11:13 UTC, sigridjineth commented
위즈님 안녕하세요? 저는 시그리드입니다. 앞으로 5주 동안 함께할 시간이 기대됩니다.

먼저 당부할 사항을 드리면:
• 언제든 코드리뷰 요청을 주셔도 좋습니다. 마치 숙제 제출하는 것처럼 완료가 되었다고 생각했을 때 리뷰 요청을 주실 필요는 없고 기능 단위로 리뷰 요청을 주셔도 좋습니다.
• 제가 일정 상 바로바로 리뷰를 봐드릴 수는 없지만 48시간(2일) 이내에 리뷰를 완료할 수 있도록 노력하겠습니다.
• 궁금하신 점이 있으시면 별도로 DM을 남겨주시면 감사드리겠습니다.

마지막으로, 학습 기간 중 건강과 행복을 최우선으로 하시기를 당부드립니다.

감사합니다!

2023-04-01 11:16 UTC, sigridjineth commented
> 제가 중간에 코드를 처음부터 새로 작성해서 커밋 내용은 [스프링 카페1 1단계 회원가입 기능 새로 구현]부터 봐주시면 감사하겠습니다!!
이렇게 작업되었을 경우 과거 커밋은 정리하시는 것이 좋습니다. PR 과정에서 알아보기 힘들기 때문입니다.
git에서 `rebase` 또는 `squash`, `drop commit` 이라는 키워드에 대해 알아보세요.

2023-04-01 12:37 UTC, realsigridjin requested changes
LGTM. 수고 많으셨습니다.
몇 가지 신경써야 할 지점들이 있어 커멘트를 달아드렸는데 현재 구현 수준 자체는 괜찮은 것 같아요.
Request Changes 드렸으니 한 번 커멘트 확인해보시고 저에게 생각을 알려주세요.

2023-04-01 12:37 UTC, realsigridjin commented on src/main/java/kr/codesqaud/cafe/MvcConfig.java
> +        registry.setOrder(Ordered.HIGHEST_PRECEDENCE);
해당 코드가 어떤 점에서 필요한가요? View Controllers의 순서를 정하시려는 이유가 어떤 것일까요?

2023-04-01 12:37 UTC, realsigridjin commented on src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
> +    Optional<User> findByUserID(String uerID);
```suggestion
    Optional<User> findByUserID(String userID);
```

2023-04-01 12:37 UTC, realsigridjin commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +                , userDto.getEmail(), userDto.getNickname(), userDto.getPassword(), user.getSignUpDate()));
Linting 기능을 사용하지 않는 것으로 보이는데 IntelliJ에서 naver coding convention 도입을 권장드려요.
https://bestinu.tistory.com/64

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +        User user = new User(++index, userDto.getUserID()
index를 여기서 추가하기 보다는.. index를 increment하는 별도의 로직이 분리되어 존재하는 것은 어떨까요?
다시 말해 Repository 입장에서 `save` method에서 직접 index를 increment를 해서 새로운 User를 만드는 역할을 하기 보다는 Repository는 정말 객체 자체를 Repository에 저장만 하는 로직이 있는 것이 좋을 것 같아요. 메소드의 로직을 세세하게 나누는 것이 좋다고 생각합니다.

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +        int userIndex = Math.toIntExact(user.getIndex()-1);
이 로직이 다소 이해가 되지 않습니다. User 객체에 있는 index 값을 가지고 List에서 꺼내오겠다는 것으로 보이는데, 만약 List에서 User 객체가 지워져도 index로 접근하는 로직에 영향이 없을까요?

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +        int userIndex = Math.toIntExact(user.getIndex()-1);
지금은 서버 1대로 동작하기 때문에 문제가 되지 않지만 다수의 서버가 하나의 `userList` 에 index로 접근하려고 했을 때 문제가 발생할 소지가 있어보입니다... race condition에 대해 시간이 나시면 한번 살펴보세요.

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy.MM.dd");
매번마다 `DateTimeFormatter` 객체를 생성하는 구조인데 이렇게 만들기 보다는 최초에 `final` 로 선언해서 상수로 만드는 것이 비용 측면에서 효율적일 것 같아요.

```java
private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy.MM.dd");
```

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +            throw new IllegalStateException("이미 존재하는 회원 닉네임입니다.");
별도의 Exception 타입을 만들어서 해당 메소드에서 난 오류임을 명확하게 밝혀주시는 것이 좋습니다.
예를 들어 `DuplicateUserException` 처럼 만들어서 사용할 수 있겠습니다.

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +        return userList.stream()
스트림의 사용이 훌륭합니다. 혹시 스트림에 대해서 어떻게 생각하시나요? for loop로 처리해도 되지 않을까요?

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +    public Optional<User> findByUserID(String uerID) {
Optional이 비용이 비싸다고 합니다. 그럼에도 사용해야 할 이유가 있다면 무엇일까요?
그리고 Java에만 Optional이 있습니다. 동일한 GC 기반의 언어인 Go의 경우에는 존재하지 않아요. 왜 그럴까요?

2023-04-01 12:37 UTC, sigridjineth commented on src/main/resources/static/js/dataValidation.js
> +const check = [false, false, false];
명확하게 해당 리스트가 뭘 하는 아이인지에 대해 변수명을 명확하게 밝혀주시는 게 좋을 것 같습니다.
이렇게만 봐서는 파악이 어렵습니다.

2023-04-01 12:37 UTC, sigridjineth commented on src/main/resources/static/js/dataValidation.js
> +        document.getElementById('emailMessage').innerText = "올바른 이메일 형식입니다.";
정규표현식을 적용하여 email verification을 하는 코어 로직과 화면에 표시하는 뷰 로직이 현재 하나로 합쳐져 있습니다.
이를 분리하는 방법에 대해 고민해보세요.

2023-04-01 12:37 UTC, sigridjineth commented on src/main/resources/static/js/dataValidation.js
> +        document.querySelector('#emailMessage').style.color = "red";
DOM을 지금 여러 번 불러오고 있는데 비용 측면에서 효율적인 접근이 아니라고 생각합니다.
다음과 같이 바꾸는 것을 제안드립니다.
```javascript
const emailMessageElement = document.querySelector('#emailMessage');
emailMessageElement.innerText = "잘못된 이메일 형식입니다.";
emailMessageElement.style.color = "red";
```

2023-04-01 12:37 UTC, sigridjineth commented on src/main/resources/static/js/dataValidation.js
> +        let write = new Object;
객체를 새로 할당할 때 웬만해서는 `let` 대신에 `const` 를 사용하는 습관을 들여보세요.

```javascript
const write = new Object;
const commentArrayData = new Array;
const commentData = new Object;
```

그리고 저라면 array literal를 사용할 것 같아요.

```javascript
const write = {};
const commentArrayData = [];
const commentData = {};
```

2023-04-01 12:37 UTC, sigridjineth commented on src/main/resources/static/js/dataValidation.js
> +        let comment = JSON.parse(localStorage.getItem("comment"));
local storage에 저장하는 메소드도 별도로 나눠볼 수 있겠네요.
```javascript
function saveDataToLocalStorage(board, comment) {
    localStorage.setItem("board", JSON.stringify(board));
    localStorage.setItem("comment", JSON.stringify(comment));
}
```

2023-04-01 12:37 UTC, sigridjineth commented on src/main/resources/static/js/dataValidation.js
> +        let write = new Object;
음 저라면 메소드를 좀 나눌 것 같습니다. 일단 basic 형태의 object 초기화하는 메소드를 만들어서 분리하겠습니다.
```javascript
function createWriteObject(title, content, date, nickname) {
    return {
        title,
        content,
        hits: 0,
        date,
        nickname,
    };
}
```

2023-04-01 12:37 UTC, sigridjineth commented on src/main/resources/static/js/dataValidation.js
> +        document.getElementById('writingMessage').innerText = "제목은 공란일 수 없고 글 내용은 3글자 이상 1000 글자 이하여야 합니다.";
여기서도 DOM을 다수 호출하는 로직이 있는데 다음과 같이 바꾸면 좋을 것 같아요.
```javascript
const writingMessageElement = document.querySelector('#writingMessage');
```

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/repository/ArticleFormRepository.java
> +    private final List<Article> articleList = new ArrayList<>();
댓글로 `final` 키워드와 불변성에 대해 알고 계시는 것을 모두 설명해주세요.

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/repository/ArticleFormRepository.java
> +    private long index = 0L;
댓글로 Java의 wrapped class와 primitive class에 대해 알고 계시는 것을 모두 설명해주세요.

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/dto/UserDto.java
> +        this.userID = userID;
저는 리턴값이 없어도 `boolean` 이라도 리턴해서 해당 메소드가 정상 동작했다는 것을 다른 메소드에게 알려주는 것을 선호합니다.
```java
public boolean setUserID(String userID) {
        this.userID = userID;
        return true
```

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/domain/Article.java
> +    private Long hits = 0L;
여기는 `long` 이 아니라 `Long` 을 사용하셨네요. 그 이유가 무엇일까요?

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +    @GetMapping("/user/list")
메소드에서는 복수의 User가 반환되는데 `/users/list` 라고 명시하는 것이 좋지 않을까요?

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +    @Autowired
생성자 주입인데도 `@Autowired` 어노테이션이 필요한가요?

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    @GetMapping("/")
article의 리스트를 반환하는 API 스펙이니 `/articles` 라고 리소스를 명시해주는 것이 좋겠습니다.

2023-04-01 12:37 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/UserConfig.java
> +    @Bean
혹시 `@Configuration` 어노테이션과 `@Bean` 그리고 `@Component` 세 가지의 차이에 대해 알고 계시나요? 학습해 보세요.

2023-04-02 21:52 UTC, sigridjineth approved these changes

2023-04-02 23:19 UTC, merged

2023-04-04 16:28 UTC, Jeongwisdom reviewed
안녕하세요, 시그리드! 위즈입니다.
제가 저번 코드스쿼드 프리코스 때 자바 공부를 처음 시작했고 스프링도 지난주에 김영한님 입문편을 보며 처음 공부했기 때문에 부족한 점이 많습니다ㅠㅠ 그런데 꼼꼼히 살펴보시고 좋은 피드백 주셔서 정말 감사합니다!!! 해주신 코드 리뷰 보며 고칠 부분 모두 제 나름대로 변경 완료하였습니다. 이번 주 미션인 DB 연결하는 것을 내일부터 진행한 후 한 번에 PR 보내겠습니다~~
오늘도 좋은 하루 보내시길 바랍니다:)

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/MvcConfig.java
> +        registry.setOrder(Ordered.HIGHEST_PRECEDENCE);
사실 루카스 2단계 미션 프로그래밍 요구사항에 매핑할 때 특별한 로직이 없는 경우 WebMVCConfigurer 적용하면 매번 메소드를 만드는 단점을 보완할 수 있다는 내용을 보고 적용시켜보았습니다. 그래서 해당 코드의 경우 우선순위를 가장 높게 잡는다는 내용을 생각해보지 못했었는데 저의 경우에는 필요없을 것 같기도 합니다... 다음부터는 주어진 내용의 코드를  쓸 때 한줄한줄 생각해보고 사용해야겠습니다ㅠㅠ

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
> +    @GetMapping("/")
넵 MvcConfig에서 /일 때 /articles로 가도록 해준 후 해당 코드는 "/articles"로 명시하여 조금 더 확실히 알 수 있도록 변경했습니다!

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +    @GetMapping("/user/list")
네 복수의 사용자의 리스트를 반환해주는 것이니 ```/users/list```라고 명시해줬어야 할 것 같습니다ㅠㅠ 변경 완료했습니다!!

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/domain/Article.java
> +    private Long hits = 0L;
스프링 강의를 보며 처음 사용해보고 있는데 강의에서 index 관련 부분을 Long으로 사용하시길래 왜그러지? 생각만 하고 모든 숫자의 경우 Long으로 그냥 따라서 써보았는데 무분별하게 제 생각없이 따라하는 것을 지양해야겠습니다... 도메인 객체의 index의 경우는 특정 시점에 존재할 수 도 있고 존재하지 않을 수도 있기 때문에 long이 아닌 Long을 사용하며 변수가 null이 아닌 것이 보장된다면 long을 사용하는 것이 좋습니다. 따라서 제 조회수 hits의 경우는 null이 아닌 것이 보장되기 때문에 long을 사용했어야 할 거 같습니다! 그리고 index의 경우도 생성자에서 값을 받아 생성하기 때문에 null이 아닌 것이 보장된다고 생각됩니다. 따라서 index도 long으로 바꿔주어도 괜찮지않을까..?라는 생각이 듭니다.

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/dto/UserDto.java
> +        this.userID = userID;
오 메소드를 이런 방식으로 정상 동작했다는 것을 알려줄 수 있는 것을 처음 알았습니다. 모두 변경 완료했습니다!

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
> +    Optional<User> findByUserID(String uerID);
오타 있는 것을 발견하지 못했는데 알려주셔서 감사합니당. 변경 완료했습니다!!

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/resources/static/js/dataValidation.js
> +const check = [false, false, false];
아직 메소드나 변수의 이름 짓는 것이 어려워서 올바르게 변경했을지는 모르겠지만 회원가입 형식이 올바른지 확인하는 배열이라 validSignUpCheck라고 변경했습니다. 그리고 밑의 글쓰기 형식이 올바른지 확인하는 배열은 validWriteCheck라고 변경하였습니다.

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +    @Autowired
저는 spring 4.3 이후부터는 생성자 주입에서 생성자가 1개만 있을 경우 ```@Autowired``` 어노테이션이 생략 가능한 것을 몰랐습니다. 변경 완료했습니다!

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/UserConfig.java
> +    @Bean
```@Configuration```은 기존의 config 형식의 파일들을 java.class 형태로 작성할 수 있도록 도와주는 어노테이션으로 내부에 ```@Component```가 정의되어 있습니다.
```@Bean```은 ```@Configuration```와 세트로 개발자가 컨트롤이 불가능한 외부 라이브러리들을 bean으로 등록하고 싶은 경우 사용합니다. ```@Target```이 METHOD로 지정되어 있지만 TYPE이 없어 메서드 단위로 지정 가능하며 개발자가 작성한 메서드를 통해 반환되는 객체(인스턴스)를 수동으로 bean 등록을 해줍니다.
```@Component```는 ```@Target```이 TYPE으로 지정되어 class 위에서만 선언이 가능하며 즉, 개발자가 직접 작성한 클래스를 bean으로 등록하고자 할 경우 사용합니다. 스프링이 런타임시 ComponentScan을 하여 자동으로 bean을 찾고 등록해줍니다.
김영한님의 강의에서 repository의 경우 다른 repository로 변경할 예정이라 ```@Configuration```과  ```@Bean```을 사용하여 수동으로 등록해주었고 저 또한 db를 따로 연결하기 때문에 이 부분은 변경이 용이하도록 수동으로 등록해주는게 맞지 않을까 생각하여 따라해보았습니다.

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/repository/ArticleFormRepository.java
> +    private final List<Article> articleList = new ArrayList<>();
```final``` 키워드는 초기에 한 번 할당을 하면 최종 값이 되어 프로그램 실행 중에 값을 바꿀 수 없도록 불변을 확보해주는 키워드입니다. 하지만 참조 타입인 객체나 컬렉션은 재할당만 제한할 뿐 무조건 불변을 보장해주지는 않습니다.
 제 경우에는 리스트가 불변일 필요가 없어 final 키워드가 필요 없는데 인텔리제이에서 느낌표로 final일지 모른다고 뜨는 알림이 떠서 생각없이 final 키워드를 넣어준 것 같습니다. 변경 완료했습니다!

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/repository/ArticleFormRepository.java
> +    private long index = 0L;
- wrapper class
  - Map<T>, List<T> 등에서 사용하는 generic 클래스는 객체에서만 작동하며 primitive type들을 지원하지 않아 실제 필요한 값 데이터를 감싸고 캡슐화하여 객체로 사용할 수 있게 할 용도로 사용
  - 실제 값 대신 Heap 공간에 저장된 객체에 대한 참조가 저장되어 오버헤드로 인해 상대적으로 접근 속도가 느림
  - 산술 연산 불가능
  - Null 사용 가능
- primitive class
  - 변수의 값을 그대로 저장
  - Null 초기화 불가능
  - 산술 연산 가능
  - Stack 메모리에 저장되어 접근이 매우 빠름

제가 index를 증가시켜주기 때문에 ++index를 해주는 건 산술 연산이기 때문에 여기서는 primitive class로 해줘야 할 것 같습니다.

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy.MM.dd");
오 이런 관점에서 생각을 해본적이 없는데 좋은 방법인 것 같습니다. 변경 완료했습니당!

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +        User user = new User(++index, userDto.getUserID()
넵 시그리드 말씀처럼 Repository는 객체 자체를 Repository에 저장만 하는 로직이 있는 것이 좋은 것 같아 새로운 User를 만드는 역할은 Service가 하도록 Service 객체를 만들어 주었고 거기서 index를 increment하는 메소드도 별도로 만들어 로직을 세세하게 나누어 변경했습니다!

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +                , userDto.getEmail(), userDto.getNickname(), userDto.getPassword(), user.getSignUpDate()));
이런 기능은 처음 봤는데 도입해봤는데 편리하네요ㅎㅎㅎ 알려주셔서 감사합니다~~

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +        int userIndex = Math.toIntExact(user.getIndex()-1);
제가 자바 공부를 한지 별로 되지 않아 지식이 많이 없어서 아직 잘 모르겠습니다...ㅠㅠ 그래서 제가 이해한 것이 맞을지 모르겠지만 html action에서 index와 회원가입일 값을 받아와서 그 값을 가지고 User 객체를 새로 생성하면 해결할 수 있지 않을까 싶어 이런 방식으로 변경했습니다.

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +    public Optional<User> findByUserID(String uerID) {
Optional은 null을 반환하면 오류가 발생할 가능성이 매우 높은 경우에 '결과없음'을 명확하게 드러내기 위해 메소드의 반환 타입으로 사용되도록 설계되었습니다. 따라서 NPE가 발생하지 않도록 도와주고 null 체크를 직접 하지 않아도 되기 때문에 사용합니다.
 Go언어에는 변수를 선언할 때, 따로 특정 값을 할당하지 않으면 자동으로 부여되는 값인 zero value가 있습니다. string, boolean, 숫자 모두 nil (다른 언어에서의 null)이 아닌 다른값들이 zero value로 선언되어 있기 때문에, 따로 초기화 하지 않아도 Nil Pointer Exception 이 나지 않습니다. 제 생각에는 이런 이유 때문에 Go의 경우에는 존재하지 않는 것 같은데 정확하게는 잘 모르겠습니다ㅠㅠ

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +        return userList.stream()
이 스트림은 김영한님의 입문편 강의를 보고 같은 로직을 사용해도 되는 부분이라 따라했습니다...ㅠ 저는 아직 스트림 사용이 미숙해서 depth 제한이 있지 않은 한은 for loop로 처리하긴 합니다. 그래도 스트림을 공부한 사람이 코드를 보면 가독성이 높아지고 코드도 짧아져서 좋다고 생각합니다. 하지만 속도가 느려질 수 있고 디버그가 어려워  적절히 사용해야하지 않을까 싶습니다.

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/resources/static/js/dataValidation.js
> +        document.querySelector('#emailMessage').style.color = "red";
네! DOM을 여러 번 불러온다는 생각 자체를 못했었습니다. 변경 완료했습니다!

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/resources/static/js/dataValidation.js
> +        document.getElementById('emailMessage').innerText = "올바른 이메일 형식입니다.";
네 맞게 리팩토링한 것인지 모르겠지만 화면에 표시하는 뷰 로직이 중복되어 계속 나오기 때문에 뷰 로직을 따로 함수로 만들어 분리해보았습니다.

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/resources/static/js/dataValidation.js
> +        document.getElementById('writingMessage').innerText = "제목은 공란일 수 없고 글 내용은 3글자 이상 1000 글자 이하여야 합니다.";
넵! 위에서 고치면서 전부 변경했습니다!!

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/resources/static/js/dataValidation.js
> +        let write = new Object;
오 좋은 방법인 것 같습니다. 변경했습니다~

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/resources/static/js/dataValidation.js
> +        let comment = JSON.parse(localStorage.getItem("comment"));
넵 시그리드 덕분에 메소드들이 간결해지는 것을 느끼고 있습니다. 자바스크립트는 잘 모른다는 마음가짐으로 메소드를 나눌 생각도 못한 것을 반성하게 됩니다ㅠㅠ 변경 완료했습니다.

2023-04-04 16:28 UTC, Jeongwisdom commented on src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
> +            throw new IllegalStateException("이미 존재하는 회원 닉네임입니다.");
네! ```DuplicateUserException```을 따로 만들어서 오류를 명확하게 밝힐 수 있도록 변경했습니다!

2023-04-04 22:45 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/controller/UserController.java
> +    @GetMapping("/user/list")
생각해보니 list 라는 어구도 부릴요하네요 users에 대한 GET이면 충분히 의미 전달이 될 것 같아요

2023-04-04 22:50 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/domain/Article.java
> +    private Long hits = 0L;
Java에서 primitive class와 wrapper class에 대한 고민은 학습자들 사이에서 많이 이루어지는데요 어떤 정답이 있는 것은 아니고 각각의 장단점을 알고 사용하는 것이 중요합니다 아래 문서를 읽어보세요

```
We recommend that you declare consistently-named identifier attributes on persistent classes and that you use a nullable (i.e., non-primitive) type.
```

https://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#entity-pojo-identifier

2023-04-04 22:53 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/repository/ArticleFormRepository.java
> +    private final List<Article> articleList = new ArrayList<>();
재할당과 불변성의 차이는 무엇일까요 객체의 설계에서 불변성이 중요하다고 이야기하는 이유는 무엇일까요

2023-04-04 22:55 UTC, sigridjineth commented on src/main/java/kr/codesqaud/cafe/repository/ArticleFormRepository.java
> +    private long index = 0L;
Wrapper Class를 이용해도 산술 연산을 수행할 수 있지 않나요