Feature/step3
codesquad-members-2023/be-java-cafe-max pull request #46
Opened 2023-03-31 09:16 UTC by JJONSOO

안녕하세요 Brian 이번에 코드리뷰를 받게된 June입니다. 잘 부탁드립니다.<br>

# 구현 목록

- <b> 회원가입
- <b> 회원 정보 수정
- <b> 회원 프로필 정보 보
- <b> 글 작성
- <b> 글 조회
- <b> 글 목록 조회

# 실행 결과

<b>초기 페이지
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/75569293/229075237-538ab3c6-3673-44e1-ae13-b50d3fc72a50.png">

<b>회원 가입 페이지
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/75569293/229075406-b084214d-d0d9-499f-bcf0-9f14fa039a52.png">
<b>회원 가입 후
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/75569293/229075506-6cda91e5-bf94-4019-ac95-138f454fb179.png">
<b>프로필 페이지
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/75569293/229075874-bd0e6048-0cf8-4cd7-bcbb-ded4748d0275.png">
<b>프로필 수정 페이지
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/75569293/229076030-8e9c9a6f-1f0c-4836-a177-af97e5f1954a.png">
<b>프로필 수정 후 페이지
<img width="1096" alt="image" src="https://user-images.githubusercontent.com/75569293/229076170-0679a814-a2f3-4a5b-ac37-fa64a6e89429.png">
<b>글쓰기 페이지
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/75569293/229075626-bc5ab509-8fe7-4111-a765-dab1c31e59d9.png">
<b>글쓴 후 메인 페이지
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/75569293/229075738-effb2c5a-a581-4cb0-b283-0d78649be070.png">

# 구현하지 못한 점

<b> 예외처리 ( ex) 동일한 UserName이 존재하는 경우, 회원정보 수정할 때, password 확인을 안함 )

# 아쉬운 점

<b> 메서드 명을 깔끔하게 못지었다.
<b> Readme 작성이 부실하다.

2023-04-01 14:24 UTC, wheejuni requested changes
수고하셨습니다. 🙇 
몇 가지 의견 드렸으니 확인 부탁드려요. 👍

2023-04-01 14:24 UTC, wheejuni commented on src/main/java/kr/codesqaud/cafe/domain/article/dto/ArticleSaveRequestDto.java
> +	String content;
너무 열려있는 듯합니다! `private` 이어도 되지 않을까 싶군요.

2023-04-01 14:24 UTC, wheejuni commented on src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleRepository.java
> +	Article findById(Integer id);
id에 맞는 `Article` 이 없을땐 어떻게 되나요?

2023-04-01 14:24 UTC, wheejuni commented on src/main/java/kr/codesqaud/cafe/domain/article/repository/impl/MemoryArticleRepositoryImpl.java
> +	private static Integer autoIncrement = 0;
- `autoIncrement` 라는 변수명이 대단히 모호하게 느껴집니다.
- `Integer` 로 충분한지 모르겠어요. 나중에 서비스가 커지면 바꿔도 된다고 생각하실 지 모르겠으나, 이런 종류의 변경은 쉬운 일이 아닙니다. 처음부터 `Long` 을 사용하시는 것이 어떨까요?

2023-04-01 14:24 UTC, wheejuni commented on src/main/java/kr/codesqaud/cafe/domain/user/entity/User.java
> +	String dateTime;
`dateTime` 이 문자열 형태로 관리되는 것에 의견 드립니다.
- 데이터의 본질은 `LocalDateTime` 이 아닐까요?
- 만약 그렇다면, 이 데이터를 받아서 사용하는 쪽에서 그 가공이 적절하게 돼야 하는 것 아닐까요?

2023-04-03 03:14 UTC, JJONSOO commented on src/main/java/kr/codesqaud/cafe/domain/article/dto/ArticleSaveRequestDto.java
> +	String content;
확인 후 수정하였습니다.

2023-04-03 03:15 UTC, JJONSOO commented on src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleRepository.java
> +	Article findById(Integer id);
Optional 객체로 감싸준 후 ,  null 이면 오류를 발생하도록 수정하였습니다.

2023-04-03 03:17 UTC, JJONSOO commented on src/main/java/kr/codesqaud/cafe/domain/article/repository/impl/MemoryArticleRepositoryImpl.java
> +	private static Integer autoIncrement = 0;
변수명을 id로 바꾼 후
AtomicLong 을 사용하여 동시성 문제도 해결하였습니다.

2023-04-03 03:18 UTC, JJONSOO commented on src/main/java/kr/codesqaud/cafe/domain/user/entity/User.java
> +	String dateTime;
User, Article 객체에서 LocalDateTime으로 바꾼 후
User, Aritcle 데이터를 가공하는 ResponseDto 에서 가공하도록 수정하였습니다.

2023-04-04 05:10 UTC, merged