[ Albert ] Step3-DB에 저장하기(미완성)
codesquad-members-2023/be-java-cafe-max pull request #86
Opened 2023-04-06 09:22 UTC by AlbertImKr

## 안녕하세요 . Jane🤩🤩🤩🤩
![image](https://ssl.pstatic.net/sstatic/keypage/outside/scui/greeting_card/img/180509_card/hello_2_3.png)

구현내용🧑‍💻
---
- Feedback 적용 했습니다.
   - 주말에 한번 정리하려고 합니다. 
- Repository를 DB로 연결 했습니다.
- Exception 처리했습니다.
- Amazon 배포했습니다.

고민내용🧐
---
- 언제, 누구 , 왜 에러를 던져야 하는 가에 대하여 고민을 많이  했습니다.
  - 잘못된 URL에 대하여 Error페이지와 매핑 하도록 예외 처리를 했습니다.
  - 사용자의 입력오류로 인한 오류는 Optional를 사용하여 재 입력 처리를 했습니다. 대신 로그를 남기도록 했습니다.
  - 자료도 많이 찾아봤는데 아직 잘 모르겠어요.
  
아쉬운 점😞
---
- Spirng JDBC로만 DB 구성해야 해요.
- 다음 미션에 Session이 있어서 이번 미션에서 Users와 Posts를 Foreign key로 묶지 못했어요.
- 화면이 너무 안 예쁘요.(무조건 개선할 예정)

다음주 계획⏰
---
- Spring JPA로 변환 해보려고 합니다.
- 조회 Query는 Query DSL 사용 해보려고 합니다.
- Users와 Posts를 관계를 묶으려고 합니다.

URL Convention🗺️
---
| url                    | method | 기능                                |
|------------------------|--------|-----------------------------------|
| /users/login           | get    | 로그인 페이지 요청                        |
| /users/login           | post   | 로그인 요청                            |
| /users/join            | get    | 회원 가입 페이지 요청                      |
| /users                 | post   | 회원 가입 요청                          |
| /users/{userId}        | get    | 회원 프로필 페이지 요청                     |
| /users/{userId}/update | get    | 회원 프로필 설정 페이지 요청                  |
| /users/{userId}/update | put    | 회월 프로필 설정 요청                      |
| /users                 | get    | 모든 회원 맴버 페이지 요청                   |
| /posts/new,/posts/form | get    | 게시글 작성 페이지 요청                     |
| /posts                 | post   | 게시글 추가 요청                         |
| /                      | get    | 모든 게스글 표시되는 메인 페이지 요청             |                    
| /posts/{postId}        | get    | 게시글의 페이지 요청                       |

2023-04-06 14:58 UTC, jinny-l commented
앨버트 AWS 배포하는 거 별로 안 어려우셨나요?? 나중에 하신다더니 뚝딱하셨네요.

저는 새로운 개념에 대해 학습할 때 많이 헤매고 시간도 오래 걸리는데, 
앨버트는 항상 뚝딱뚝딱 빨리 해내시는 것 보면 대단하다고 생각이 들어요.
특히 이번주가 저는 많이 헤매서 많이 못한 것 같은데 앨버트는 정말 많이 구현하셔서 대단합니다...

2023-04-06 17:17 UTC, janeljs requested changes
Albert 안녕하세요~ㅎㅎ
![image](https://user-images.githubusercontent.com/68000537/230447003-0506e8be-a312-4c4c-b531-93bd0ca51ba4.png)

빠르게 PR 주셨네요~ 쉽지 않으셨을텐데 고생하셨습니다 💯 
고민하시는 지점과 추가로 고민해보셨으면 좋겠는 부분들 코멘트로 남겼으니 생각해보시고 답변 주세요 😄 
이번에는 빠르게 작업해주신 덕분에 머지 전까지 반영할 수 있는 시간이 있으실 것 같아 RC드립니다ㅎㅎ

2023-04-06 17:17 UTC, janeljs commented on README.md
> +| /users/{userId}/update | put    | 회월 프로필 설정 요청                      |
https://github.com/codesquad-members-2023/be-java-cafe-max/pull/1/files#r1155154437
질문에 대한 답변을 받지 못하였는데요~ㅎㅎ `update`를 url에 포함시키신 이유가 궁금합니다.
폼 조회 페이지와의 url 통일성 때문인가요?

2023-04-06 17:17 UTC, janeljs commented on README.md
> +- chore: Changes to the build process or tools and libraries such as documentation generation
👍🏻

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserService.java
> +    public boolean containEmail(String email) {
리뷰 반영이 안된 것 같아요~ㅎㅎ https://github.com/codesquad-members-2023/be-java-cafe-max/pull/1/files#r1155157429

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/JoinFormValidator.java
> +            errors.rejectValue(EMAIL, "error.email.duplicate");
JoinFormValidator로 validation 로직을 분리해주셨군요~ㅎㅎ 지금은 이메일 검증만 있어서 조금 과한 느낌도 있는 거 같은데 추후에 검증 로직이 많이 생기면 관리가 쉬워지겠네요 👍🏻

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +@RequestMapping("/users")
nit: 공통부분을 `@RequestMapping`으로 분리해주셨군요~ 이렇게 하면 중복 코드가 줄어드는 장점이 있기는 한데요.
인텔리제이에서 api 전체 url로 검색할 때 나오지 않고, path 가독성이 오히려 떨어지는 것 같아 개인적으로는 선호하지 않습니다ㅎㅎ

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
>  @Controller
`@RestController`와 `@Controller`의 차이점에 대하여 학습해보세요~

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +    @InitBinder("joinForm")
`@InitBinder`를 사용하셨군요 👍🏻 joinForm 지정도 잘해주셨네요ㅎㅎ

보너스로ㅎㅎ 아래와 같이 선언해주면 어떤 일이 일어날까요?(힌트 키워드: setter)
```java
@ControllerAdvice
public class WebControllerAdvice {

    @InitBinder
    public void initBinder(WebDataBinder binder) {
        binder.initDirectFieldAccess();
    }
}
```

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +    public String addUser(@Valid JoinForm joinForm, BindingResult bindingResult) {
`@Validated`와는 어떤 차이점이 있을까요~?

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserService.java
> +    public int saveNewUser(JoinForm joinForm) {
new는 없어도 될 것 같아요~ https://github.com/codesquad-members-2023/be-java-cafe-max/pull/1/files#r1155154619 코멘트 보고 save로 바꾸신 것 같은데요ㅎㅎ `join` 등을 생각하고 드린 코멘트이기는 했습니다.
그런데 이거는 Service와 Repository 간 네이밍을 통일하게 팀 컨벤션을 정할 수도 있는 거고해서 통일성만 갖춰주신다면 `saveUser`도 괜찮을 것 같아요ㅎㅎ

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/exception/SaveUserFailedException.java
> +public class SaveUserFailedException extends CustomException {
예외의 이름들이 조금 어색한 것 같아요. 여러 사례를 찾아보고 개선해보세요~

2023-04-06 17:17 UTC, janeljs commented on src/main/resources/messages_ko.properties
> +error.email.notExist=\uC774\uBA54\uC77C\uC774 \uC874\uC7AC\uD558\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.
흠.. 인코딩 설정 어떤 거로 되어있으세요?

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/dto/ProfileSettingForm.java
> +    }
이 생성자는 어디 쓰이고 있나요?

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +        userService.update(profileSettingForm, userId);
가독성도 안좋고 서비스에서 처리해야 할 로직이 Controller에 있는 것 같아요.
그리고 불필요한 DB 조회도 발생하구요.
`userService.isDuplicateEmail(form.getEmail())`, `userService.checkPassword(form.getPassword())` 이런식으로 되도록 리팩토링해보는 건 어떨까요? 

+ 비밀번호 암호화에 대해서도 나중에 생각해보세요ㅎㅎ

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +    }
여러군데 걸쳐서 있는 것 같은데 user와 member를 혼용해서 쓰시는 이유가 있나요?

2023-04-06 17:17 UTC, janeljs commented on src/test/java/kr/codesqaud/cafe/account/UserControllerTest.java
> +@Transactional
테스트에 `@Transactional`을 붙이면 어떻게 동작하나요~?

2023-04-06 17:17 UTC, janeljs commented on src/test/java/kr/codesqaud/cafe/account/UserControllerTest.java
>  		mockMvc.perform(put("/users/20/update")
여기는 왜 userId 값이 하드코딩 되어있나요?

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +            logger.info("[ Message = {} ],[ Id = {} ]", NO_SUCH_POST_ID_CODE.getMessage(), postId);
로깅 level info가 적합할까요?

2023-04-06 17:17 UTC, janeljs commented on src/test/resources/application.properties
> +spring.datasource.password=
jasypt를 이용해서 중요 정보를 암호화해보세요~

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/exception/ErrorCode.java
> +public enum ErrorCode {
ㅎㅎ 고생하셨어요~ 💯

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/exception/ErrorCode.java
> +    NO_SUCH_POST_TITLE_CODE(HttpStatus.NOT_FOUND, "PD004", "해당 Post 타이틀이 존재하지 않습니다.", "error/custom"),
전부 커스텀 에러 페이지로 보내도 괜찮을까요? (서비스 화면으로 이동되어야 하는 경우는 없나요?)

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +    public static final String QUERY_FIND_BY_TITLE = "SELECT POST_ID , NICKNAME, TITLE, TEXT_CONTENT, CREATE_DATETIME FROM POST WHERE TITLE = ?";
named parameter에 대해 공부해보시는 것도 좋을 것 같네요ㅎㅎ

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/config/ValidatorConfig.java
> +    MessageSource messageSource;
접근제어자가 누락된 것 같네요~

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +    public static final String QUERY_SELECT_ALL = "SELECT * FROM POST";
쿼리에서 `*`를 사용하는 것은 지양하는게 좋습니다. 컬럼을 명시해주세요.

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +        this.jdbcTemplate = new JdbcTemplate(dataSource);
생성자로 생성하지 않고 JdbcTemplate을 주입받을 수는 없을까요?

2023-04-06 17:17 UTC, janeljs commented on src/main/resources/schema.sql
> +CREATE TABLE users
`user`가 좋을 것 같아요ㅎㅎ 왜그런지 이유도 생각해보세요~

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +        }
DataAccessException을 공통으로 잡고있는 수많은 try catch와 로깅에 대하여 중복 제거를 해줄 수 있는 방법을 생각해보세요~ㅎㅎ 이미 비슷한 걸 구현하신게 있습니다.

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/User.java
> +    private User(Builder builder) {
private으로 선언해주신 것 좋아요~

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserRepository.java
> +    private static final String QUERY_CONTAINS_EMAIL = "SELECT COUNT(*) FROM USERS WHERE EMAIL = ?";
이렇게 되면 email이 있는지 확인하기 위해 전체를 확인해야 하는데요. 개선할 수는 없을까요?

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserRepository.java
> +    public void update(User user) {
이렇게 update를 따로 해줘도 되지만 upsert라는 개념도 있습니다. 참고삼아 공부해보세요ㅎㅎ

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +        }
컨트롤러에서 수행되어야 할 로직일까요?

2023-04-06 17:17 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(CustomException.class)
지금은 CustomException으로 묶어서 처리하고 있지만 앞으로 적절하게 상속구조를 이용하여 예외를 계층화하거나 그룹핑해서 처리해도 좋을 것 같습니다ㅎㅎ

2023-04-06 21:37 UTC, AlbertImKr commented
> 앨버트 AWS 배포하는 거 별로 안 어려우셨나요?? 나중에 하신다더니 뚝딱하셨네요.
> 
> 저는 새로운 개념에 대해 학습할 때 많이 헤매고 시간도 오래 걸리는데, 앨버트는 항상 뚝딱뚝딱 빨리 해내시는 것 보면 대단하다고 생각이 들어요. 특히 이번주가 저는 많이 헤매서 많이 못한 것 같은데 앨버트는 정말 많이 구현하셔서 대단합니다...

- AWS 는 깊게 공부하지는 못했고 블로그 따라 한번 해봤습니다. 일단 책을 구매했고 읽어 볼 예정입니다.  
- 저는 아무래도 전에 이미 강의를 다 들어봤습니다. 기술을 조금 알고 있는 상태이여서 조금 빨리 할 수 있는 것 같습니다.
- 감사합니다.

2023-04-06 21:42 UTC, AlbertImKr commented
> ### Albert 안녕하세요~ 🤩
> ![image](https://user-images.githubusercontent.com/68000537/230447003-0506e8be-a312-4c4c-b531-93bd0ca51ba4.png)
> 
> 빠르게 PR 주셨네요~ 쉽지 않으셨을텐데 고생하셨습니다 💯 고민하시는 지점과 추가로 고민해보셨으면 좋겠는 부분들 코멘트로 남겼으니 생각해보시고 답변 주세요 😄 이번에는 빠르게 작업해주신 덕분에 머지 전까지 반영할 수 있는 시간이 있으실 것 같아 RC드립니다ㅎㅎ

- 혼자서 많이 고민했고 답을 찾을 수 없어서 도움을 요청한것입니다. 🙇🏻‍♂️ 
- 남겨주신 코멘트로 보면서 찾아보고 해결해보겠습니다. 🤩🤩🤩

2023-04-06 23:01 UTC, AlbertImKr commented on README.md
> +| /users/{userId}/update | put    | 회월 프로필 설정 요청                      |
🤦‍♂️🤦‍♂️Comment를 놓쳤습니다. 제 실수 입니다.
- 전체적으로 한번 더 확인 해보겠습니다.

2023-04-06 23:04 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserService.java
> +    public int saveNewUser(JoinForm joinForm) {
🤦‍♂️🤦‍♂️🤦‍♂️ 이 통일하도록 하겠습니다.  gitHub가 리뷰시스템을 아직 익숙하지 않아서 많은 Comment를 확인 못했습니다.

2023-04-07 03:05 UTC, AlbertImKr commented on README.md
> +| /users/{userId}/update | put    | 회월 프로필 설정 요청                      |
💡이렇게 개선하겠습니다.

개인 프로필 페이지
HttpRequsetMethod GET
/users/{userId} -> /users/{userId}/profile
/users/{userId} 를 개인 정보 페이지로 구성하려고 수정했습니다.
개인 프로필 수정 페이지
HttpRequsetMethod Get
/users/{userId}/update -> /users/{userId}/profile/edit
개인 프로필 수정 요청
HttpRequestMethod Put
/users/{userId}/update -> /users/{userId}/profile

2023-04-07 03:06 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserService.java
> +    public boolean containEmail(String email) {
수정했습니다.

2023-04-07 03:13 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/JoinFormValidator.java
> +            errors.rejectValue(EMAIL, "error.email.duplicate");
- Validator을 한번 사용해봤습니다.  
- Validator은 역할이 어디 까지인지 고민하고 있습니다.
     - 예를 들면 로그인 로직에서
          - 로그인시 입력 타입을 검증한다.
          - 존재하는 아이디 인지 검증한다.
          - 비밀번호가 체크한다. 
    - 이 모든 것을 Validator에서 모두 검증하여도 되나요?

2023-04-07 03:15 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +@RequestMapping("/users")
저도 분리하는 것이 조금 가독성이 떨어진다고 생각은 들었습니다. 다른 리뷰어 분의 코멘트를 보고 수정했습니다. 저 다시 돌려 놓겠습니다.🤩🤩🤩

2023-04-07 03:31 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
>  @Controller
- @RestController는 @Controller + @ResponseBody 이라고 알고 있습니다. 
- String 반환하는 Controller입니다. 
- 조금 더 찾아보고 정리하고 알아보겠습니다. 📚

2023-04-07 07:35 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +    @InitBinder("joinForm")
- DataBinder 의 기본 설정은 `initBeanPropertyAccess()` 입니다. JavaBean property access로 객체를 초기화한다. 즉 setter 사용하여 초기화 한다.
- `initDriectFiedlAccesss()` 로 설정하면 reflection을 통해서 직접 필드를 access하여 초기화 한다. 즉 setter를 사용하지 않고 초기화 한다.

2023-04-07 07:47 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +    public String addUser(@Valid JoinForm joinForm, BindingResult bindingResult) {
@Valid 는 javax의 에노테이션으로서 java표준의 에노테이션입니다. @Validated 는 Spring의 에노테이션입니다. 지금 상상할수 없겠지만 Spring framwork를 자른 framwork로 변경할 때 @Valid를 사용 했으면 이점이 있습니다.

2023-04-07 08:07 UTC, AlbertImKr commented on src/main/resources/messages_ko.properties
> +error.email.notExist=\uC774\uBA54\uC77C\uC774 \uC874\uC7AC\uD558\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.
- 국제화 resource를 사용했는데 한글이 깨져서 Intellij 에서 encoding UTF-8로 설정했고 Transparent native-to-ascii conversion했습니다. 코드가 이렇게 올라가는 것을 이제 알았습니다.🧐🧐
<img width="579" alt="스크린샷 2023-04-07 오후 5 06 00" src="https://user-images.githubusercontent.com/99056666/230569246-f93b6d5d-4b77-49fc-87d3-dd3f01b4ce8e.png">

2023-04-07 08:08 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/exception/SaveUserFailedException.java
> +public class SaveUserFailedException extends CustomException {
고민하고 개선해보겠습니다.

2023-04-07 08:19 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/dto/ProfileSettingForm.java
> +    }
- form에서 Setter를 모두 제거했고 Builder로 생성자를 구현하여 DataBinder할 때 사용 하고 있습니다.

2023-04-07 08:21 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +    }
통일 하도록 하겠습니다.

2023-04-07 08:28 UTC, AlbertImKr commented on src/test/java/kr/codesqaud/cafe/account/UserControllerTest.java
> +@Transactional
- 테스트 후 Rollback 을 합니다. 실행된 query가 모두 취소된다고 알고 있습니다.

2023-04-07 08:29 UTC, AlbertImKr commented on src/test/java/kr/codesqaud/cafe/account/UserControllerTest.java
>  		mockMvc.perform(put("/users/20/update")
- 저장한 userId 받고 ++userId 를 사용하여 20을 대체했습니다.

2023-04-07 08:29 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/exception/ErrorCode.java
> +public enum ErrorCode {
감사합니다. 🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️

2023-04-07 12:46 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +        userService.update(profileSettingForm, userId);
- `userService.isDuplicateEmail(form.getEmail())` 
      -  email로 DB 조회 하면 될 것 같습니다.
 - `userService.checkPassword(form.getPassword())`
      -  이 부분은 어떻게 해결 할지 모르겠어요.  힌트 주실수 있을 까요 ?😭

2023-04-07 21:45 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +            logger.info("[ Message = {} ],[ Id = {} ]", NO_SUCH_POST_ID_CODE.getMessage(), postId);
- Id 없을 때 발생하는 에러이라고 생각했습니다. 그래서 Id 가 없을 수 있는 것은 매우 정상적이 일이라고 생각해서 info를 사용했습니다. 
- 각 레벨의 개념은 찾아서 봤는데 현 단계 info 이상의 레벨을 사용해야 하는 필요성을 느끼지 못했습니다.
- 항상 기준을 잡는 것이 제일 힘든 부분이라고 생각합니다.😭

2023-04-07 22:17 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +        userService.update(profileSettingForm, userId);
- 이렇게 수정했습니다.
- DB 조회는 두번은 해야 한다고 생각합니다.
     - Email 중복 체크
     - Password 일치 체크

Controller
``` java
        if (userService.isDuplicateEmail(profileSettingForm.getEmail())) {
            bindingResult.rejectValue(EMAIL, "error.email.duplicate");
            loggingError(bindingResult);
            return "account/profileUpdate";
        }
        if (!userService.isSamePassword(userId,profileSettingForm.getPassword())) {
            bindingResult.rejectValue(PASSWORD, "error.password.notMatch");
            loggingError(bindingResult);
            return "account/profileUpdate";
        }
```
Service
``` java
    public boolean isDuplicateEmail(String targetEmail) {
        return userRepository.findByEmail(targetEmail).isEmpty();
    }

    public boolean isSamePassword(Long userId, String targetPassword) {
        Optional<User> userOptional = userRepository.findById(userId);
        return userOptional.map(user -> user.isSamePassword(targetPassword)).orElse(false);
    }
```

2023-04-07 22:55 UTC, AlbertImKr commented on src/test/resources/application.properties
> +spring.datasource.password=
넵. 암호화 해보겠습니다.🧑‍💻

2023-04-07 23:01 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/exception/ErrorCode.java
> +    NO_SUCH_POST_TITLE_CODE(HttpStatus.NOT_FOUND, "PD004", "해당 Post 타이틀이 존재하지 않습니다.", "error/custom"),
- Exception을 던져서 Error view 가 아닌 일반 컨트롤러 view(예: 로그인 페이지)로 연결하는 방법은 좋은 방법 일 까요?
```java
@ExceptionHandler(LoginException.class)
public ModelAndView handler(....){
          
         modelAndView.addObject("email","email 오류")
         return "users/login";
}
```

2023-04-07 23:06 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +    public static final String QUERY_FIND_BY_TITLE = "SELECT POST_ID , NICKNAME, TITLE, TEXT_CONTENT, CREATE_DATETIME FROM POST WHERE TITLE = ?";
- named parameter도 사용해봤습니다.

2023-04-07 23:07 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/config/ValidatorConfig.java
> +    MessageSource messageSource;
🤦‍♂️🤦‍♂️🤦‍♂️ 수정하겠습니다.

2023-04-07 23:08 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +    public static final String QUERY_SELECT_ALL = "SELECT * FROM POST";
- 수정하겠습니다.🧑‍💻🧑‍💻🧑‍💻

2023-04-08 09:14 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +        this.jdbcTemplate = new JdbcTemplate(dataSource);
가능합니다.
- Spring jdbc를 사용시 `@Autowired` 를 사용하면 바로 사용 가능합니다.
- ```java
    @Autowired
    private JdbcTemplate jdbcTemplate;
    @Autowired
    private NamedParameterJdbcTemplate namedParameterJdbcTemplate;

- dataSource를 주입하지 않고 바로 생성자 주입도 가능합니다.

- ```java
    private final JdbcTemplate jdbcTemplate;
  
    private final NamedParameterJdbcTemplate namedParameterJdbcTemplate;
    
    
    public UserRepository(JdbcTemplate jdbcTemplate, NamedParameterJdbcTemplate namedParameterJdbcTemplate) {
              this.jdbcTemplate = jdbcTemplate;
              this.namedParameterJdbcTemplate = namedParameterJdbcTemplate;
    }
```

2023-04-08 12:20 UTC, AlbertImKr commented on src/main/resources/schema.sql
> +CREATE TABLE users
감사합니다. 확인 했습니다. 

- https://stackoverflow.com/questions/338156/table-naming-dilemma-singular-vs-plural-names

2023-04-08 12:23 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +        }
- Exception에 대하어 더 공부하고 수정해보겠습니다.😭😭
   - 혹시 추천할 Blog나 참고자료가 있을 까요?

2023-04-08 12:25 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/User.java
> +    private User(Builder builder) {
감사합니다. 🙇🏻‍♂️

2023-04-08 14:26 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserRepository.java
> +    private static final String QUERY_CONTAINS_EMAIL = "SELECT COUNT(*) FROM USERS WHERE EMAIL = ?";
이렇게 개선했습니다. 🕵️🕵️
- ```SELECT COUNT(email) FROM USERS WHERE EMAIL = ?```

2023-04-08 14:53 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserRepository.java
> +    public void update(User user) {
- 감사합니다. 🙇🏻‍♂️🙇🏻‍♂️찾아보고 공부해보겠습니다.

2023-04-08 15:08 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(CustomException.class)
넵
- Exception 계층화와 그룹핑를 한번 찾아보고 적용해보겠습니다. 🧑‍💻🧑‍💻🤦‍♂️

2023-04-08 15:10 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +        }
- 컨틀롤러로 이동하겠습니다.

2023-04-08 22:21 UTC, janeljs approved these changes
Albert 리뷰 하나하나 확인하고 반영하시느라 정말 고생 많으셨습니다~ㅎㅎㅎ
이번 PR은 여기서 머지하고, 남겨주신 코멘트랑 수정사항은 차차 꼼꼼히 확인해볼게요 😄

2023-04-08 22:23 UTC, merged

2023-04-08 22:29 UTC, AlbertImKr commented
> Albert 리뷰 하나하나 확인하고 반영하시느라 정말 고생 많으셨습니다~ㅎㅎㅎ 이번 PR은 여기서 머지하고, 남겨주신 코멘트랑 수정사항은 차차 꼼꼼히 확인해볼게요 😄

- 저의 코드를 항상 꼼꼼히 체크해주시고 리뷰를 남겨주셔서 감사합니다.🙇🏻‍♂️🙇🏻‍♂️

2023-04-09 02:16 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
>  @Controller
네~ㅎㅎ spring mvc에서 DispatcherServlet으로 요청이 들어와서 사용자에게 반환되기까지 어떤 과정이 있는지도 같이 학습해보세요~ㅎㅎ

> String 반환하는 Controller입니다.
이거는... `@Controller`에서 view name 반환한다고 말씀주신 것 맞죠..?ㅎㅎㅎ

RestController에 왜 "Rest"가 붙었는지와 응답 포맷도 함께 생각해보세요~

2023-04-09 02:20 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +    @InitBinder("joinForm")
굳굳 잘 학습하셨네요~ㅎㅎ

2023-04-09 02:28 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
>  @Controller
> 이거는... @Controller에서 view name 반환한다고 말씀주신 것 맞죠..?ㅎㅎㅎ

문자열을  반환한다고 표현하고 싶었습니다.  🫣
- JSON형식
- 그냥 String 문자열

2023-04-09 02:34 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
>  @Controller
@Controller에서 string 문자열 말고 ModelAndView를 리턴할 때도 있어서요ㅎㅎ 결국에는 string도 ModelAndView로 담기게 spring이 처리해주지만요ㅎㅎㅎ

참고: https://stackoverflow.com/questions/25988442/what-is-the-difference-between-return-modelandview-and-return-string-in-spring-m

2023-04-09 05:12 UTC, jinny-l commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +@RequestMapping("/users")
> nit: 공통부분을 `@RequestMapping`으로 분리해주셨군요~ 이렇게 하면 중복 코드가 줄어드는 장점이 있기는 한데요. 인텔리제이에서 api 전체 url로 검색할 때 나오지 않고, path 가독성이 오히려 떨어지는 것 같아 개인적으로는 선호하지 않습니다ㅎㅎ

@janeljs 
api 전체 url로 검색할 때가 shift 두번 눌렀을 때를 말씀하시는 것일까요?

2023-04-09 13:50 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +        }
```java
//controller
    @PostMapping("/users/login")
    public String login(@Valid LoginForm loginForm, BindingResult bindingResult) {
        if (bindingResult.hasErrors()) {
            loggingError(bindingResult);
            return "account/login";
        }
        Long userId = userService.login(loginForm, bindingResult);
        if (bindingResult.hasErrors()) {
            return "account/login";
        }
        return "redirect:/users/" + userId + "/profile";
    }
```
```java
//service
    public Long login(LoginForm loginForm, BindingResult bindingResult) {
        Optional<User> userOptional = findByEmail(loginForm.getEmail());
        if (userOptional.isEmpty()) {
            loggingError(bindingResult);
            bindingResult.rejectValue(EMAIL, "error.email.notExist");
            return -1L;
        }
        User user = userOptional.get();
        if (!user.getPassword().equals(loginForm.getPassword())) {
            loggingError(bindingResult);
            bindingResult.rejectValue(PASSWORD, "error.password.notMatch");
            return -1L;
        }
        return user.getId();
    }
```

2023-04-10 15:37 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +    @InitBinder("joinForm")
>3. 인터페이스, 추상 클래스 또는 매핑된 슈퍼클래스에서 getter 및 setter를 선언하고 구체적인 서브클래스에서 override할 수 있습니다. 임시 계약을 정의하는 것이 더 쉽습니다.

이 부분은 제가 잘 이해를 못했는데 임시계약을 정의하는게 더 쉽다는게 무슨 뜻인가요?ㅎㅎ

2023-04-10 15:51 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +        }
> 컨트롤러로 이동하겠습니다.

서비스로 이동 말씀해주신 것 맞죠?!ㅎㅎ

2023-04-10 15:58 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +        }
몇 가지 코멘트 드리고 싶은게 있는데요ㅎㅎ

1. optional은 굳이 변수명에 적어주지 않으셔도 됩니다.
2. bindingResult는 form validation에만 사용해주시고, db 조회가 필요한 로직은 service에서 적절한 예외를 던져주세요.
bindingResult로 처리하면 좋은 로직들은 아래와 같습니다.
![image](https://user-images.githubusercontent.com/68000537/230940362-f3393a79-6d23-4a2d-b760-ea6891c613fe.png)
출처: https://web.archive.org/web/20161120115428/http://codetutr.com/2013/05/28/spring-mvc-form-validation/

2023-04-10 16:05 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +    public String addUser(@Valid JoinForm joinForm, BindingResult bindingResult) {
`@Validated`에서만 지원되는 기능들도 있기는 한데요ㅎㅎ 잘 사용하지는 않아서 지금 정도의 학습도 좋은 것 같습니다. 👍🏻

2023-04-10 16:33 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/JoinFormValidator.java
> +            errors.rejectValue(EMAIL, "error.email.duplicate");
음..이 부분은 정답은 없습니다. 말씀하신 로직들 다 validator에서 처리해도 괜찮고, 일부는 서비스에서 일부는 validator에서 하셔도 괜찮습니다.
복잡한 비즈니스 로직이 많아서 서비스가 엄청 비대해져 로직을 관리하기 어려울 때가 있는데요.
그럴 때 CQRS로 서비스를 분리하여도 괜찮고, validate 관련 로직은 validator로 넣어도 괜찮습니다.

> Spring has come up with a Validator interface that is both basic and eminently usable in every layer of an application.

validator 인터페이스가 도입될 때 어플리케이션의 모든 layer에서 사용될 수 있게 만들어졌다고 하네요ㅎㅎ

https://docs.spring.io/spring-framework/docs/2.5.5/reference/validation.html

2023-04-10 16:37 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +@RequestMapping("/users")
앗 이부분은 cmd + shift + f 로 검색했을 때를 말씀드린 건데요ㅎㅎ shift 두 번 눌러서 전체검색 할때는 잘 나옵니다ㅎㅎ

&rarr; 저는 개인적으로 너무 길지 않다면 full path를 쓰는 것이 가독성에 더 좋다고 생각하지만 온전히 취향의 영역이라 @RequestMapping으로 중복코드를 제거해주시는 것도 좋은 방법인 것 같습니다.

2023-04-10 16:54 UTC, janeljs commented on src/main/resources/messages_ko.properties
> +error.email.notExist=\uC774\uBA54\uC77C\uC774 \uC874\uC7AC\uD558\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.
`transparent native-to-ascii conversion` 옵션을 적용하지 않아도 처음 파일 입력 시 인코딩이 utf-8로 지정되어 있으셨다면 push본도 한글로 잘 보이고 로컬에서도 한글로 잘 보일 것 같은데요ㅎㅎ 해당 옵션을 적용하신 이유가 있었을까요?!

2023-04-10 16:55 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/dto/ProfileSettingForm.java
> +    }
빌더에서는 아래 생성자만 사용되는 것 같아 여쭤보았습니다~ㅎㅎ
```java
  private ProfileSettingForm(Builder builder) {
        this.email = builder.email;
        this.nickname = builder.nickname;
        this.password = builder.password;
    }
```

2023-04-10 17:03 UTC, janeljs commented on src/main/resources/templates/account/members.html
> +                                    th:onclick="|location.href='@{/users/{id}/update(id = ${userForm.id})}'|">수정
url 수정이 안된 것 같아요~

2023-04-10 17:13 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +        userService.update(profileSettingForm, userId);
`불필요한 DB 조회`는 아래 부분에 대한 코멘트였습니다ㅎㅎ
```java
  User user = userService.findById(userId);
        if (userService.isDuplicateEmail(user.getEmail(), profileSettingForm.getEmail()))
```
```java
public boolean isDuplicateEmail(String targetEmail) {
        return userRepository.findByEmail(targetEmail).isPresent();
    }
```

아래와 같이 개선하신 것 확인했는데요ㅎㅎ
```java
        if (userService.isDuplicateEmail(profileSettingForm.getEmail())) {
            bindingResult.rejectValue(EMAIL, "error.email.duplicate");
            loggingError(bindingResult);
            return "account/profileUpdate";
        }
        if (!userService.isSamePassword(userId,profileSettingForm.getPassword())) {
            bindingResult.rejectValue(PASSWORD, "error.password.notMatch");
            loggingError(bindingResult);
            return "account/profileUpdate";
        }
```
service에서 중복검사를 처리하고, 예외를 던진 후 해당 예외를 잡아 bindingResult에서 처리하거나, exception handler에서 처리하도록 개선해주세요ㅎㅎ

2023-04-10 17:26 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +        userService.update(profileSettingForm, userId);
앗 이부분 제가 깊게 생각하지 않고 제안을 드린 것 같습니다 😢 
위에 해주신 것처럼 user에게 물어보는 형태로 `user.isSamePassword`와 같이 개선해주신 것 좋습니다 👍🏻 

+ 이 부분도 service에서 중복검사를 처리하고, 예외를 던진 후 해당 예외를 잡아 controller에서 bindingResult로 처리하거나, exception handler에서 처리하도록 개선해주세요ㅎㅎ

2023-04-10 17:36 UTC, janeljs commented on src/test/java/kr/codesqaud/cafe/account/UserControllerTest.java
> +@Transactional
롤백을 해주기는 하는데요ㅎㅎ auto increment 컬럼은 이미 증가한 값 그대로 유지될 거예요ㅎㅎ 한 번 확인해보시고 알려주세요~ㅎㅎ

2023-04-10 17:49 UTC, janeljs commented on src/test/java/kr/codesqaud/cafe/account/UserControllerTest.java
>  		mockMvc.perform(put("/users/20/update")
뭔가 자연스러운 방법은 아닌 것 같습니다.
차라리 static 상수로 NON_EXISTING_USER_ID = 2; 이런식으로 선언해주시고 사용하시는 건 어떨까요?

2023-04-10 18:10 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +            logger.info("[ Message = {} ],[ Id = {} ]", NO_SUCH_POST_ID_CODE.getMessage(), postId);
본인만의 타당한 이유를 가지고 설정해 주신 것 좋습니다 💯 
말씀주신대로 개발자가 이미 예상할 수 있는 예외 상황이라서 info 레벨 정도면 충분한 것 같네요ㅎㅎ

+ 로깅 레벨에 대한 다양한 토론이 있어 첨부드립니다.
참고: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels

2023-04-10 19:18 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/exception/ErrorCode.java
> +    NO_SUCH_POST_TITLE_CODE(HttpStatus.NOT_FOUND, "PD004", "해당 Post 타이틀이 존재하지 않습니다.", "error/custom"),
> Exception을 던져서 Error view 가 아닌 일반 컨트롤러 view(예: 로그인 페이지)로 연결하는 방법은 좋은 방법 일 까요?

해당 예외들이 발생했을 때 사용자에게 전부 커스텀 에러 페이지가 보이는게 맞는가(?)하는 의문에서 위와 같은 코멘트를 드려봤습니다.
예를 들어 로그인을 하지 않은 사용자가 특정 포스트를 수정하려고 해서 수정 불가능한 post라는 예외가 발생했다고 가정했을 때는 에러페이지를 보여주기보단 로그인 페이지로 보내주는게 좋지 않나 라는 생각을 해보았습니다ㅎㅎ

위와 같은 상황에 대한 처리는 따로 되어있고, 커스텀 에러페이지를 보여주는 것이 더 나은 상황이라면 상황에 맞는 에러 페이지를 적절하게 구현하여 지금과 같이 enum에서 관리하고 있는 viewname을 리턴하도록 처리해주는 것도 좋은 방법입니다 👍🏻

2023-04-10 19:31 UTC, janeljs commented on src/main/resources/schema.sql
> +CREATE TABLE users
아하 그런 배경이 있었군요ㅠㅠ 혹시 double quote로 감싸도 안되나요?
> There is a list of keywords that can't be used as identifiers (table names, column names and so on), unless they are quoted (surrounded with double quotes). 

http://www.h2database.com/html/advanced.html

아래와 같이도 사용할 수 있다는데 키워드에서 인위적으로 제외하는게 뭔가 좋아보이지는 않네요..
```yml
spring:
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER
```

2023-04-10 20:24 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +        }
간단하게 @ControllerAdvice를 이용한 global exception handler에서 `DataAccessException`을 잡아서 해결할 수 있을 것 같아요ㅎㅎ
```java
  // Specify name of a specific view that will be used to display the error:
  @ExceptionHandler({SQLException.class,DataAccessException.class})
  public String databaseError() {
    // Nothing to do.  Returns the logical view name of an error page, passed
    // to the view-resolver(s) in usual way.
    // Note that the exception is NOT available to this view (it is not added
    // to the model) but see "Extending ExceptionHandlerExceptionResolver"
    // below.
    return "databaseError";
  }
```
참고: https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc

2023-04-10 20:26 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +        }
그리고 공부하시는 겸에ㅎㅎㅎ `SQLErrorCodeSQLExceptionTranslator`가 jdbcTemplate에서 어떤 역할을 해주었는지도 공부해보세요ㅎㅎ

https://docs.spring.io/spring-framework/docs/3.0.x/spring-framework-reference/html/jdbc.html#jdbc-SQLExceptionTranslator

2023-04-10 20:27 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserRepository.java
> +    private static final String QUERY_CONTAINS_EMAIL = "SELECT COUNT(*) FROM USERS WHERE EMAIL = ?";
흐음.. 저는 column 말고 row의 관점에서 전체를 말씀드린 거긴 했습니다ㅎㅎ 지금 email이 있는지 없는지만 알면 되는데 몇 개 있는지까지 조회하는 쿼리가 필요할까요?

2023-04-10 20:28 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(CustomException.class)
네ㅎㅎ 저도 아무것도 모를 때 적은 글이라 부끄럽기는 한데 아래 글도 참고해보세요ㅋㅋ
https://velog.io/@janeljs/codesquad-tech-talk-1

2023-04-10 23:58 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +    @InitBinder("joinForm")
initDirectFieldAccess() 만 가능하다고 생가하였는데 찾아보니까 그런 내용이 아닌것 같습니다. 🤦‍♂️

2023-04-10 23:59 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +    public String addUser(@Valid JoinForm joinForm, BindingResult bindingResult) {
`@Validated` 지원되는 기능들도 한번 찾아보겠습니다.

2023-04-11 00:10 UTC, AlbertImKr commented on src/main/resources/messages_ko.properties
> +error.email.notExist=\uC774\uBA54\uC77C\uC774 \uC874\uC7AC\uD558\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.
- 처음 국제화 메시지를 사용 할 때 한글이 깨져서 방법을 찾아봤습니다. 
- Transparent native-to-sacii conversion의 의믜를 제대로 이해하지 못했습니다. 👍

2023-04-11 00:45 UTC, AlbertImKr commented on src/test/java/kr/codesqaud/cafe/account/UserControllerTest.java
> +@Transactional
- 트랜잭션을 롤백해도 여전히 기본 키가 증가합니다.
- auto increment  자동 증가 값을 생성하는 데 사용되는 잠금 모드와 관련이 있습니다. 
- Insert문에 할 때 atuo increament을 할당하여 실행한다. insert Transation의 속하지 않아 rollback할 수 없다고 이해했습니다.

> https://stackoverflow.com/questions/449346/mysql-auto-increment-does-not-rollback

2023-04-11 00:48 UTC, AlbertImKr commented on src/test/java/kr/codesqaud/cafe/account/UserControllerTest.java
>  		mockMvc.perform(put("/users/20/update")
좋은 방법인 것 같습니다. 👍

2023-04-11 00:58 UTC, AlbertImKr commented on src/main/resources/schema.sql
> +CREATE TABLE users
- 아직 배울 것이 많네요.

2023-04-11 01:00 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/post/PostRepository.java
> +        }
감사합니다. 🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️

2023-04-11 02:43 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserController.java
> +        }
개선 해보겠습니다.

2023-04-11 02:47 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler(CustomException.class)
감사합니다. 🙇🏻‍♂️🙇🏻‍♂️

2023-04-11 02:53 UTC, AlbertImKr commented on src/main/resources/templates/account/members.html
> +                                    th:onclick="|location.href='@{/users/{id}/update(id = ${userForm.id})}'|">수정
넵. 🤦‍♂️

2023-04-13 02:49 UTC, janeljs commented on src/main/java/kr/codesqaud/cafe/account/UserRepository.java
> +    private static final String QUERY_CONTAINS_EMAIL = "SELECT COUNT(*) FROM USERS WHERE EMAIL = ?";
아래 글도 참고해보세요~ㅎㅎ
https://jojoldu.tistory.com/516

2023-04-13 02:53 UTC, AlbertImKr commented on src/main/java/kr/codesqaud/cafe/account/UserRepository.java
> +    private static final String QUERY_CONTAINS_EMAIL = "SELECT COUNT(*) FROM USERS WHERE EMAIL = ?";
넵 감사합니다. 😭